const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),{DatabaseSync}=require('node:sqlite');
const ROOT=__dirname, PUBLIC=path.join(ROOT,'public'), UPLOADS=path.join(ROOT,'uploads'), DATA=path.join(ROOT,'data');
for(const d of [PUBLIC,UPLOADS,DATA]) fs.mkdirSync(d,{recursive:true});
const db=new DatabaseSync(process.env.DATABASE_PATH||path.join(DATA,'revolt.db')); db.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;');
const schema=fs.readFileSync(path.join(ROOT,'schema.sql'),'utf8'); db.exec(schema);
db.exec(`
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY,name TEXT NOT NULL,category TEXT,description TEXT,price REAL NOT NULL DEFAULT 0,stock INTEGER NOT NULL DEFAULT 0,image TEXT,status TEXT DEFAULT 'Active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY,customer_id INTEGER REFERENCES users(id),order_no TEXT UNIQUE NOT NULL,total REAL NOT NULL DEFAULT 0,status TEXT DEFAULT 'Pending Payment',payment_method TEXT,payment_status TEXT DEFAULT 'Pending',delivery_address TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY,order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id INTEGER REFERENCES products(id),name TEXT,price REAL,qty INTEGER);
CREATE TABLE IF NOT EXISTS services(id INTEGER PRIMARY KEY,name TEXT NOT NULL,description TEXT,price_from REAL DEFAULT 0,icon TEXT,status TEXT DEFAULT 'Active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS service_requests(id INTEGER PRIMARY KEY,customer_id INTEGER REFERENCES users(id),service_id INTEGER REFERENCES services(id),name TEXT,phone TEXT,vehicle TEXT,preferred_date TEXT,notes TEXT,status TEXT DEFAULT 'New',amount REAL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS agents(id INTEGER PRIMARY KEY,name TEXT NOT NULL,email TEXT,phone TEXT,image TEXT,bio TEXT,status TEXT DEFAULT 'Active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS conversations(id INTEGER PRIMARY KEY,customer_id INTEGER REFERENCES users(id),subject TEXT,context_type TEXT,context_id TEXT,status TEXT DEFAULT 'Open',assigned_to TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS chat_messages(id INTEGER PRIMARY KEY,conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,sender_type TEXT NOT NULL,sender_id INTEGER,message TEXT NOT NULL,attachment TEXT,created_at TEXT NOT NULL,read_at TEXT);
CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY,order_id INTEGER REFERENCES orders(id),service_request_id INTEGER REFERENCES service_requests(id),reference TEXT UNIQUE,method TEXT,amount REAL,status TEXT DEFAULT 'Pending',provider TEXT DEFAULT 'Configured at hosting',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
`);
try{db.exec('ALTER TABLE vehicles ADD COLUMN old_price REAL DEFAULT 0')}catch{}

const now=()=>new Date().toISOString(), json=(res,code,obj)=>{res.writeHead(code,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(obj))};
const parseBody=req=>new Promise((resolve,reject)=>{let b='';req.on('data',d=>{b+=d;if(b.length>35e6)req.destroy()});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}})});
const hash=p=>{const salt=crypto.randomBytes(16).toString('hex');return salt+':'+crypto.scryptSync(p,salt,64).toString('hex')};
const verify=(p,h)=>{if(!h)return false;const [s,k]=h.split(':');return crypto.timingSafeEqual(Buffer.from(k,'hex'),crypto.scryptSync(p,s,64))};
function seed(){let n=db.prepare('SELECT count(*) n FROM users').get().n;if(!n){db.prepare('INSERT INTO users(name,email,password_hash,role,created_at) VALUES(?,?,?,?,?)').run('Revolt Administrator',process.env.ADMIN_EMAIL||'admin',hash(process.env.ADMIN_PASSWORD||'admin'),'super_admin',now())}
if(!db.prepare('SELECT count(*) n FROM vehicles').get().n){const ins=db.prepare(`INSERT INTO vehicles(title,make,model,year,price,location,mileage,transmission,fuel,engine,body_type,color,condition,status,label,description,highlights,notes,featured,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);[
['2024 Toyota Corolla LE','Toyota','Corolla',2024,185000,'Kumasi',45000,'Automatic','Petrol','1.8L','Sedan','Silver','Foreign Used','Available','VERIFIED','Clean, efficient sedan with strong everyday usability.','Low mileage|Fuel efficient|Reverse camera','Minor cosmetic wear may be present.',1],
['2023 Mercedes-Benz C300','Mercedes-Benz','C300',2023,520000,'Accra',21000,'Automatic','Petrol','2.0L','Sedan','Black','Foreign Used','Available','HOT DEAL','Premium sedan with modern comfort and technology.','Leather seats|Sunroof|Apple CarPlay','Inspection recommended before purchase.',1],
['2022 Hyundai Tucson','Hyundai','Tucson',2022,245000,'Tema',38000,'Automatic','Petrol','2.0L','SUV','White','Foreign Used','Available','NEW ARRIVAL','Practical SUV with comfortable cabin and useful technology.','Reverse camera|Parking sensors|Android Auto','Verify service records during inspection.',1],
['2021 Honda Civic Touring','Honda','Civic',2021,210000,'Accra',51000,'Automatic','Petrol','1.5L Turbo','Sedan','Blue','Foreign Used','Reserved','VERIFIED','Sporty compact sedan with premium trim.','Sunroof|Leather seats|Apple CarPlay','Currently reserved.',0],
['2023 Toyota RAV4 XLE','Toyota','RAV4',2023,385000,'Kumasi',27000,'Automatic','Hybrid','2.5L','SUV','Grey','Foreign Used','Available','GOOD VALUE','Efficient family SUV with hybrid powertrain.','Push start|Apple CarPlay|Cruise control','Confirm hybrid battery condition at inspection.',1],
['2020 Kia Sportage EX','Kia','Sportage',2020,168000,'Takoradi',68000,'Automatic','Petrol','2.4L','SUV','Red','Locally Used','Available','PRICE REDUCED','Value-focused SUV with useful comfort features.','Leather seats|Bluetooth|Reverse camera','Review maintenance history.',0]
].forEach(v=>ins.run(...v,now(),now()));}}
seed();
if(!db.prepare("SELECT 1 FROM content_blocks WHERE key='terms'").get()) db.prepare('INSERT INTO content_blocks(key,title,subtitle,body,extra_json,updated_at) VALUES(?,?,?,?,?,?)').run('terms','Terms & Conditions','REVOLT AUTOLINK','By using Revolt AutoLink, you agree to use vehicle, store, service and communication features responsibly. Vehicle information should be independently verified during inspection. Payments, delivery and service fulfilment are subject to confirmation.', '[]', now());
if(!db.prepare('SELECT count(*) n FROM services').get().n){const q=db.prepare('INSERT INTO services(name,description,price_from,icon,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)');[['Engine Tuning','Performance diagnostics and engine tuning.',500,'⚙'],['Repairs','Mechanical and electrical repair coordination.',250,'🔧'],['Customisations','Interior, exterior and performance customisation.',500,'✨'],['General Maintenance','Routine servicing, fluids, filters and checks.',200,'🛠'],['Car Insurance','Insurance support and quotation requests.',0,'🛡'],['Vehicle Detailing','Interior and exterior detailing packages.',250,'◈']].forEach(x=>q.run(...x,'Active',now(),now()))}
if(!db.prepare('SELECT count(*) n FROM products').get().n){const q=db.prepare('INSERT INTO products(name,category,description,price,stock,image,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)');[['Premium Engine Oil','Maintenance','High quality engine oil for routine servicing.',420,20,''],['Brake Pad Set','Brakes','Front brake pad replacement set.',650,12,''],['Car Care Kit','Detailing','Wash, polish and interior care essentials.',350,25,''],['LED Headlight Pair','Lighting','Bright replacement LED headlight pair.',780,8,'']].forEach(x=>q.run(...x,'Active',now(),now()))}

if(!db.prepare("SELECT 1 FROM content_blocks WHERE key='about'").get()){db.prepare('INSERT INTO content_blocks(key,title,subtitle,body,extra_json,updated_at) VALUES(?,?,?,?,?,?)').run('about','We help you find the right car.','ABOUT REVOLT AUTOLINK','Revolt AutoLink professionally presents vehicles sourced from a growing network, helps customers compare options and coordinates inspections while keeping the vehicle at the centre of the experience.',JSON.stringify([{title:'Discover',body:'Search quality vehicle listings with useful specifications and media.'},{title:'Understand',body:'See the highlights, important notes and vehicle information before visiting.'},{title:'Inspect',body:'Request an inspection and let our team coordinate the physical visit.'},{title:'Decide',body:'Compare your shortlist and deal with the actual seller when you are ready.'}]),now())}
function token(req){let a=req.headers.authorization||'';return a.startsWith('Bearer ')?a.slice(7):''}function user(req){let t=token(req);if(!t)return null;return db.prepare('SELECT u.id,u.name,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?').get(t,now())||null}
function audit(u,action,entity,id,details=''){db.prepare('INSERT INTO audit_logs(user_id,action,entity,entity_id,details,created_at) VALUES(?,?,?,?,?,?)').run(u?.id||null,action,entity,String(id||''),details,now())}
function vehicleRows(where='1=1',params=[]){return db.prepare(`SELECT v.*, (SELECT path FROM media m WHERE m.vehicle_id=v.id AND m.type='image' ORDER BY m.is_primary DESC,m.sort_order LIMIT 1) image, (SELECT count(*) FROM favourites f WHERE f.vehicle_id=v.id) saves, (SELECT count(*) FROM enquiries e WHERE e.vehicle_id=v.id) enquiries FROM vehicles v WHERE ${where} ORDER BY v.featured DESC,v.created_at DESC`).all(...params)}
function oauthFinish(res,provider,providerId,email,name){email=String(email||'').toLowerCase();let x=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!x){let r=db.prepare('INSERT INTO users(name,email,password_hash,role,created_at) VALUES(?,?,?,?,?)').run(name,email,hash(crypto.randomBytes(32).toString('hex')),'customer',now());x=db.prepare('SELECT * FROM users WHERE id=?').get(r.lastInsertRowid);db.prepare('INSERT OR IGNORE INTO customers(name,phone,email,created_at) VALUES(?,?,?,?)').run(name,'',email,now())}db.prepare('INSERT INTO oauth_accounts(user_id,provider,provider_id,created_at) VALUES(?,?,?,?) ON CONFLICT(provider,provider_id) DO UPDATE SET user_id=excluded.user_id').run(x.id,provider,providerId,now());let t=crypto.randomBytes(32).toString('hex'),exp=new Date(Date.now()+30*864e5).toISOString();db.prepare('INSERT INTO sessions(token,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(t,x.id,exp,now());let payload=Buffer.from(JSON.stringify({token:t,user:{id:x.id,name:x.name,email:x.email,phone:'',role:'customer'}})).toString('base64url');res.writeHead(302,{location:'/?oauth='+payload+'#account'});res.end()}
async function api(req,res,u){let url=new URL(req.url,'http://x'),p=url.pathname,method=req.method;
if(p==='/api/health')return json(res,200,{ok:true,time:now()});
if(p==='/api/auth/login'&&method==='POST'){let b=await parseBody(req),x=db.prepare('SELECT * FROM users WHERE (email=? OR name=?) AND active=1').get((b.email||'').toLowerCase(),(b.email||'').trim());if(!x||!verify(b.password||'',x.password_hash))return json(res,401,{error:'Invalid email or password'});let t=crypto.randomBytes(32).toString('hex'),exp=new Date(Date.now()+7*864e5).toISOString();db.prepare('INSERT INTO sessions(token,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(t,x.id,exp,now());audit(x,'login','session',t);return json(res,200,{token:t,user:{id:x.id,name:x.name,email:x.email,role:x.role}})}
if(p==='/api/auth/me')return u?json(res,200,u):json(res,401,{error:'Unauthorized'});
const adminProtected=(p==='/api/analytics/dashboard'||p==='/api/audit'||p==='/api/customers'||(p==='/api/vehicles'&&method==='POST')||(p==='/api/vehicles'&&method==='GET'&&url.searchParams.get('admin')==='1')||(/^\/api\/vehicles\/\d+$/.test(p)&&['PUT','DELETE'].includes(method))||(['/api/enquiries','/api/inspections','/api/alerts','/api/contact','/api/car-requests'].includes(p)&&method==='GET')||((p==='/api/content/about'||p==='/api/content/terms')&&method==='PUT')||(p==='/api/payments'&&method==='GET')||(/^\/api\/(products|services|agents)\/\d+$/.test(p)&&['PUT','DELETE'].includes(method))||(['/api/products','/api/services','/api/agents'].includes(p)&&method==='POST')||(/^\/api\/chat\/conversations\/\d+\/messages$/.test(p)&&method==='POST')||(/^\/api\/vehicles\/\d+\/media$/.test(p)&&method==='POST')||(/^\/api\/media\/\d+$/.test(p)&&method==='DELETE'));if(adminProtected&&(!u||u.role!=='super_admin'))return json(res,401,{error:'Admin login required'});
if(p==='/api/oauth/config'&&method==='GET')return json(res,200,{google:!!(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET),facebook:!!(process.env.FACEBOOK_APP_ID&&process.env.FACEBOOK_APP_SECRET)});
if(p==='/api/oauth/google'&&method==='GET'){if(!process.env.GOOGLE_CLIENT_ID)return json(res,503,{error:'Google sign-in is not configured'});let base=process.env.APP_URL||(`${req.headers['x-forwarded-proto']||'http'}://${req.headers.host}`),redirect=base+'/api/oauth/google/callback',state=crypto.randomBytes(16).toString('hex');db.prepare('INSERT INTO oauth_states(state,provider,created_at) VALUES(?,?,?)').run(state,'google',now());res.writeHead(302,{location:'https://accounts.google.com/o/oauth2/v2/auth?'+new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:redirect,response_type:'code',scope:'openid email profile',state,prompt:'select_account'}).toString()});return res.end()}
if(p==='/api/oauth/google/callback'&&method==='GET'){let state=url.searchParams.get('state'),code=url.searchParams.get('code'),st=db.prepare("SELECT * FROM oauth_states WHERE state=? AND provider='google'").get(state);if(!st||!code)return json(res,400,{error:'Invalid OAuth response'});db.prepare('DELETE FROM oauth_states WHERE state=?').run(state);let base=process.env.APP_URL||(`${req.headers['x-forwarded-proto']||'http'}://${req.headers.host}`),redirect=base+'/api/oauth/google/callback';let tr=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:redirect,grant_type:'authorization_code'})}),td=await tr.json();if(!td.access_token)return json(res,401,{error:'Google sign-in failed'});let pr=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{authorization:'Bearer '+td.access_token}}),profile=await pr.json();return oauthFinish(res,'google',profile.sub,profile.email,profile.name||profile.email)}
if(p==='/api/oauth/facebook'&&method==='GET'){if(!process.env.FACEBOOK_APP_ID)return json(res,503,{error:'Facebook sign-in is not configured'});let base=process.env.APP_URL||(`${req.headers['x-forwarded-proto']||'http'}://${req.headers.host}`),redirect=base+'/api/oauth/facebook/callback',state=crypto.randomBytes(16).toString('hex');db.prepare('INSERT INTO oauth_states(state,provider,created_at) VALUES(?,?,?)').run(state,'facebook',now());res.writeHead(302,{location:'https://www.facebook.com/v23.0/dialog/oauth?'+new URLSearchParams({client_id:process.env.FACEBOOK_APP_ID,redirect_uri:redirect,state,scope:'email,public_profile'}).toString()});return res.end()}
if(p==='/api/oauth/facebook/callback'&&method==='GET'){let state=url.searchParams.get('state'),code=url.searchParams.get('code'),st=db.prepare("SELECT * FROM oauth_states WHERE state=? AND provider='facebook'").get(state);if(!st||!code)return json(res,400,{error:'Invalid OAuth response'});db.prepare('DELETE FROM oauth_states WHERE state=?').run(state);let base=process.env.APP_URL||(`${req.headers['x-forwarded-proto']||'http'}://${req.headers.host}`),redirect=base+'/api/oauth/facebook/callback';let tr=await fetch('https://graph.facebook.com/v23.0/oauth/access_token?'+new URLSearchParams({client_id:process.env.FACEBOOK_APP_ID,client_secret:process.env.FACEBOOK_APP_SECRET,redirect_uri:redirect,code})),td=await tr.json();if(!td.access_token)return json(res,401,{error:'Facebook sign-in failed'});let pr=await fetch('https://graph.facebook.com/me?'+new URLSearchParams({fields:'id,name,email',access_token:td.access_token})),profile=await pr.json();return oauthFinish(res,'facebook',profile.id,profile.email||`facebook-${profile.id}@revoltautolink.local`,profile.name||'Facebook User')}
if(p==='/api/customer/register'&&method==='POST'){let b=await parseBody(req),email=(b.email||'').trim().toLowerCase();if(!b.name||!email||!b.password)return json(res,400,{error:'Name, email and password are required'});if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return json(res,409,{error:'An account with this email already exists'});let r=db.prepare('INSERT INTO users(name,email,password_hash,role,created_at) VALUES(?,?,?,?,?)').run(b.name,email,hash(b.password),'customer',now());let t=crypto.randomBytes(32).toString('hex'),exp=new Date(Date.now()+30*864e5).toISOString();db.prepare('INSERT INTO sessions(token,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(t,r.lastInsertRowid,exp,now());db.prepare('INSERT OR IGNORE INTO customers(name,phone,email,created_at) VALUES(?,?,?,?)').run(b.name,b.phone||'',email,now());return json(res,201,{token:t,user:{id:Number(r.lastInsertRowid),name:b.name,email,phone:b.phone||'',role:'customer'}})}
if(p==='/api/customer/login'&&method==='POST'){let b=await parseBody(req),x=db.prepare("SELECT * FROM users WHERE email=? AND role='customer' AND active=1").get((b.email||'').trim().toLowerCase());if(!x||!verify(b.password||'',x.password_hash))return json(res,401,{error:'Invalid email or password'});let t=crypto.randomBytes(32).toString('hex'),exp=new Date(Date.now()+30*864e5).toISOString();db.prepare('INSERT INTO sessions(token,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(t,x.id,exp,now());let c=db.prepare('SELECT phone FROM customers WHERE email=?').get(x.email);return json(res,200,{token:t,user:{id:x.id,name:x.name,email:x.email,phone:c?.phone||'',role:x.role}})}
if(p==='/api/customer/profile'&&method==='GET'){if(!u||u.role!=='customer')return json(res,401,{error:'Unauthorized'});let c=db.prepare('SELECT phone FROM customers WHERE email=?').get(u.email);return json(res,200,{...u,phone:c?.phone||''})}
if(p==='/api/customer/profile'&&method==='PUT'){if(!u||u.role!=='customer')return json(res,401,{error:'Unauthorized'});let b=await parseBody(req);db.prepare('UPDATE users SET name=? WHERE id=?').run(b.name||u.name,u.id);db.prepare('INSERT INTO customers(name,phone,email,created_at) VALUES(?,?,?,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,phone=excluded.phone').run(b.name||u.name,b.phone||'',u.email,now());return json(res,200,{id:u.id,name:b.name||u.name,email:u.email,phone:b.phone||'',role:u.role})}
if(p==='/api/vehicles'&&method==='GET'){let q=url.searchParams.get('q')||'',status=url.searchParams.get('status')||'Available',admin=url.searchParams.get('admin')==='1';let w=admin?'1=1':'status IN (\'Available\',\'Reserved\')',params=[];if(q){w+=' AND (title LIKE ? OR make LIKE ? OR model LIKE ? OR location LIKE ?)';params.push(...Array(4).fill('%'+q+'%'))}return json(res,200,vehicleRows(w,params))}
let vm=p.match(/^\/api\/vehicles\/(\d+)$/);if(vm&&method==='GET'){let v=vehicleRows('v.id=?',[+vm[1]])[0];if(!v)return json(res,404,{error:'Not found'});db.prepare('UPDATE vehicles SET views=views+1 WHERE id=?').run(v.id);v.media=db.prepare('SELECT * FROM media WHERE vehicle_id=? ORDER BY sort_order').all(v.id);return json(res,200,v)}
if(p==='/api/vehicles'&&method==='POST'){let b=await parseBody(req);let r=db.prepare(`INSERT INTO vehicles(title,make,model,year,price,location,mileage,transmission,fuel,engine,body_type,color,condition,status,label,description,highlights,notes,featured,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(b.title||'',b.make||'',b.model||'',+b.year||0,+b.price||0,b.location||'',+b.mileage||0,b.transmission||'',b.fuel||'',b.engine||'',b.body_type||'',b.color||'',b.condition||'',b.status||'Draft',b.label||'',b.description||'',b.highlights||'',b.notes||'',b.featured?1:0,now(),now());audit(u,'create','vehicle',r.lastInsertRowid,b.title);return json(res,201,{id:Number(r.lastInsertRowid)})}
if(vm&&method==='PUT'){let b=await parseBody(req),id=+vm[1];let old=db.prepare('SELECT * FROM vehicles WHERE id=?').get(id);if(!old)return json(res,404,{error:'Not found'});let keys=['title','make','model','year','price','location','mileage','transmission','fuel','engine','body_type','color','condition','status','label','description','highlights','notes','featured'];for(let k of keys)if(b[k]!==undefined)old[k]=b[k];db.prepare(`UPDATE vehicles SET title=?,make=?,model=?,year=?,price=?,location=?,mileage=?,transmission=?,fuel=?,engine=?,body_type=?,color=?,condition=?,status=?,label=?,description=?,highlights=?,notes=?,featured=?,updated_at=? WHERE id=?`).run(...keys.map(k=>old[k]),now(),id);audit(u,'update','vehicle',id);return json(res,200,{ok:true})}
if(vm&&method==='DELETE'){db.prepare('DELETE FROM vehicles WHERE id=?').run(+vm[1]);audit(u,'delete','vehicle',+vm[1]);return json(res,200,{ok:true})}
if(p==='/api/enquiries'&&method==='POST'){if(!u||u.role!=='customer')return json(res,401,{error:'Please sign in before making an enquiry'});let b=await parseBody(req);let r=db.prepare('INSERT INTO enquiries(vehicle_id,name,phone,email,contact_method,message,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(b.vehicle_id||null,b.name,b.phone,b.email||'',b.contact_method||'WhatsApp',b.message||'','New',now(),now());return json(res,201,{id:Number(r.lastInsertRowid)})}
if(p==='/api/enquiries'&&method==='GET'){return json(res,200,db.prepare('SELECT e.*,v.title vehicle_title FROM enquiries e LEFT JOIN vehicles v ON v.id=e.vehicle_id ORDER BY e.created_at DESC').all())}
if(p==='/api/inspections'&&method==='POST'){if(!u||u.role!=='customer')return json(res,401,{error:'Please sign in before requesting an inspection'});let b=await parseBody(req);let r=db.prepare('INSERT INTO inspections(vehicle_id,name,phone,preferred_date,preferred_time,contact_method,notes,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(b.vehicle_id,b.name,b.phone,b.preferred_date,b.preferred_time,b.contact_method||'WhatsApp',b.notes||'','Pending',now(),now());return json(res,201,{id:Number(r.lastInsertRowid)})}
if(p==='/api/inspections'&&method==='GET'){return json(res,200,db.prepare('SELECT i.*,v.title vehicle_title FROM inspections i JOIN vehicles v ON v.id=i.vehicle_id ORDER BY i.created_at DESC').all())}
if(p==='/api/alerts'&&method==='POST'){let b=await parseBody(req);let criteria=JSON.stringify({query:b.query||'',make:b.make||'',model:b.model||'',budget:+b.budget||0,location:b.location||'',notes:b.notes||''});let r=db.prepare('INSERT INTO alerts(name,phone,email,criteria,status,created_at) VALUES(?,?,?,?,?,?)').run(b.name||'',b.phone||'',b.email||'',criteria,'Active',now());return json(res,201,{id:Number(r.lastInsertRowid)})}
if(p==='/api/alerts'&&method==='GET'){return json(res,200,db.prepare('SELECT * FROM alerts ORDER BY created_at DESC').all())}
if(p==='/api/contact'&&method==='POST'){let b=await parseBody(req);let r=db.prepare('INSERT INTO contact_messages(name,phone,email,message,status,created_at) VALUES(?,?,?,?,?,?)').run(b.name,b.phone||'',b.email||'',b.message,'New',now());return json(res,201,{id:Number(r.lastInsertRowid)})}
if(p==='/api/contact'&&method==='GET'){return json(res,200,db.prepare('SELECT * FROM contact_messages ORDER BY created_at DESC').all())}
if(p==='/api/car-requests'&&method==='GET'){return json(res,200,db.prepare('SELECT * FROM car_requests ORDER BY created_at DESC').all())}
if(p==='/api/car-requests'&&method==='POST'){if(!u||u.role!=='customer')return json(res,401,{error:'Please sign in before making a request'});let b=await parseBody(req);let r=db.prepare('INSERT INTO car_requests(name,phone,make,model,budget,body_type,transmission,condition,notes,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(b.name,b.phone,b.make||'',b.model||'',+b.budget||0,b.body_type||'',b.transmission||'',b.condition||'',b.notes||'','New',now());return json(res,201,{id:Number(r.lastInsertRowid)})}
if(p==='/api/customers'&&method==='GET'){return json(res,200,db.prepare('SELECT c.*, (SELECT count(*) FROM enquiries e WHERE e.email=c.email OR e.phone=c.phone) enquiries FROM customers c ORDER BY c.created_at DESC').all())}
let em=p.match(/^\/api\/enquiries\/(\d+)\/status$/);if(em&&method==='PUT'){let b=await parseBody(req);db.prepare('UPDATE enquiries SET status=?,updated_at=? WHERE id=?').run(b.status||'New',now(),+em[1]);return json(res,200,{ok:true})}
let im=p.match(/^\/api\/inspections\/(\d+)\/status$/);if(im&&method==='PUT'){let b=await parseBody(req);db.prepare('UPDATE inspections SET status=?,updated_at=? WHERE id=?').run(b.status||'Pending',now(),+im[1]);return json(res,200,{ok:true})}
if(p==='/api/content/about'&&method==='GET'){let x=db.prepare("SELECT * FROM content_blocks WHERE key='about'").get();if(!x)return json(res,404,{error:'About content not found'});try{x.items=JSON.parse(x.extra_json||'[]')}catch{x.items=[]}return json(res,200,x)}
if((p==='/api/content/about'||p==='/api/content/terms')&&method==='PUT'){let b=await parseBody(req);let extra=JSON.stringify(Array.isArray(b.items)?b.items:[]);db.prepare("INSERT INTO content_blocks(key,title,subtitle,body,extra_json,updated_at) VALUES('about',?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET title=excluded.title,subtitle=excluded.subtitle,body=excluded.body,extra_json=excluded.extra_json,updated_at=excluded.updated_at").run(b.title||'',b.subtitle||'',b.body||'',extra,now());audit(u,'update','content','about');return json(res,200,{ok:true})}
let mm=p.match(/^\/api\/vehicles\/(\d+)\/media$/);if(mm&&method==='POST'){let b=await parseBody(req),id=+mm[1];if(!db.prepare('SELECT id FROM vehicles WHERE id=?').get(id))return json(res,404,{error:'Vehicle not found'});let files=Array.isArray(b.files)?b.files:[];if(!files.length)return json(res,400,{error:'No media supplied'});let current=db.prepare('SELECT count(*) n FROM media WHERE vehicle_id=?').get(id).n,saved=[];for(let i=0;i<files.length;i++){let f=files[i]||{},m=String(f.data||'').match(/^data:(image\/(?:jpeg|png|webp)|video\/(?:mp4|webm)|audio\/(?:mpeg|mp3|wav|ogg));base64,(.+)$/);if(!m)continue;let mime=m[1],type=mime.startsWith('image/')?'image':mime.startsWith('video/')?'video':'audio',ext=mime.includes('png')?'png':mime.includes('webp')?'webp':mime.includes('webm')?'webm':mime.includes('wav')?'wav':mime.includes('ogg')?'ogg':mime.includes('mpeg')||mime.includes('mp3')?'mp3':mime.includes('mp4')?'mp4':'jpg',buf=Buffer.from(m[2],'base64'),limit=type==='image'?8*1024*1024:60*1024*1024;if(buf.length>limit)continue;let name=`vehicle-${id}-${Date.now()}-${i}.${ext}`,disk=path.join(UPLOADS,name);fs.writeFileSync(disk,buf);let publicPath='/uploads/'+name,r=db.prepare('INSERT INTO media(vehicle_id,type,category,path,is_primary,sort_order,created_at) VALUES(?,?,?,?,?,?,?)').run(id,type,f.category||type,publicPath,(type==='image'&&current===0&&i===0)?1:0,current+i,now());saved.push({id:Number(r.lastInsertRowid),path:publicPath,type,category:f.category||type})}audit(u,'upload','vehicle_media',id,`${saved.length} media file(s)`);return json(res,201,{files:saved})}
let md=p.match(/^\/api\/media\/(\d+)$/);if(md&&method==='DELETE'){let m=db.prepare('SELECT * FROM media WHERE id=?').get(+md[1]);if(!m)return json(res,404,{error:'Media not found'});if(m.path&&m.path.startsWith('/uploads/')){let f=path.join(UPLOADS,path.basename(m.path));try{fs.unlinkSync(f)}catch{}}db.prepare('DELETE FROM media WHERE id=?').run(+md[1]);return json(res,200,{ok:true})}
if(p==='/api/analytics/dashboard'){let stats={vehicles:db.prepare("SELECT count(*) n FROM vehicles WHERE status='Available'").get().n,totalVehicles:db.prepare('SELECT count(*) n FROM vehicles').get().n,enquiries:db.prepare('SELECT count(*) n FROM enquiries').get().n,inspections:db.prepare('SELECT count(*) n FROM inspections').get().n,customers:db.prepare('SELECT count(*) n FROM customers').get().n,requests:db.prepare('SELECT count(*) n FROM car_requests').get().n,alerts:db.prepare('SELECT count(*) n FROM alerts').get().n,messages:db.prepare('SELECT count(*) n FROM contact_messages').get().n,views:db.prepare('SELECT coalesce(sum(views),0) n FROM vehicles').get().n,sold:db.prepare("SELECT count(*) n FROM vehicles WHERE status='Sold'").get().n};return json(res,200,{stats,vehicles:vehicleRows('1=1').slice(0,10),recentEnquiries:db.prepare('SELECT e.*,v.title vehicle_title FROM enquiries e LEFT JOIN vehicles v ON v.id=e.vehicle_id ORDER BY e.created_at DESC LIMIT 5').all(),recentInspections:db.prepare('SELECT i.*,v.title vehicle_title FROM inspections i LEFT JOIN vehicles v ON v.id=i.vehicle_id ORDER BY i.created_at DESC LIMIT 5').all()})}
if(p==='/api/audit'){return json(res,200,db.prepare('SELECT a.*,u.name user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 100').all())}

if(p==='/api/content/terms'&&method==='GET'){let x=db.prepare("SELECT * FROM content_blocks WHERE key='terms'").get();return json(res,200,x||{})}
if(p==='/api/content/terms'&&method==='PUT'){let b=await parseBody(req);db.prepare("INSERT INTO content_blocks(key,title,subtitle,body,extra_json,updated_at) VALUES('terms',?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET title=excluded.title,subtitle=excluded.subtitle,body=excluded.body,updated_at=excluded.updated_at").run(b.title||'',b.subtitle||'',b.body||'','[]',now());audit(u,'update','content','terms');return json(res,200,{ok:true})}
if(p==='/api/products'&&method==='GET')return json(res,200,db.prepare("SELECT * FROM products WHERE status!='Deleted' ORDER BY created_at DESC").all());
if(p==='/api/products'&&method==='POST'){let b=await parseBody(req),r=db.prepare('INSERT INTO products(name,category,description,price,stock,image,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(b.name,b.category||'',b.description||'',+b.price||0,+b.stock||0,b.image||'',b.status||'Active',now(),now());return json(res,201,{id:Number(r.lastInsertRowid)})}
let pm=p.match(/^\/api\/products\/(\d+)$/);if(pm&&method==='PUT'){let b=await parseBody(req),x=db.prepare('SELECT * FROM products WHERE id=?').get(+pm[1]);if(!x)return json(res,404,{error:'Not found'});for(const k of ['name','category','description','price','stock','image','status'])if(b[k]!==undefined)x[k]=b[k];db.prepare('UPDATE products SET name=?,category=?,description=?,price=?,stock=?,image=?,status=?,updated_at=? WHERE id=?').run(x.name,x.category,x.description,+x.price,+x.stock,x.image,x.status,now(),x.id);return json(res,200,{ok:true})}
if(pm&&method==='DELETE'){db.prepare("UPDATE products SET status='Deleted',updated_at=? WHERE id=?").run(now(),+pm[1]);return json(res,200,{ok:true})}
if(p==='/api/services'&&method==='GET')return json(res,200,db.prepare("SELECT * FROM services WHERE status!='Deleted' ORDER BY id").all());
if(p==='/api/services'&&method==='POST'){let b=await parseBody(req),r=db.prepare('INSERT INTO services(name,description,price_from,icon,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(b.name,b.description||'',+b.price_from||0,b.icon||'🔧',b.status||'Active',now(),now());return json(res,201,{id:Number(r.lastInsertRowid)})}
let sm=p.match(/^\/api\/services\/(\d+)$/);if(sm&&method==='PUT'){let b=await parseBody(req),x=db.prepare('SELECT * FROM services WHERE id=?').get(+sm[1]);if(!x)return json(res,404,{error:'Not found'});for(const k of ['name','description','price_from','icon','status'])if(b[k]!==undefined)x[k]=b[k];db.prepare('UPDATE services SET name=?,description=?,price_from=?,icon=?,status=?,updated_at=? WHERE id=?').run(x.name,x.description,+x.price_from,x.icon,x.status,now(),x.id);return json(res,200,{ok:true})}
if(sm&&method==='DELETE'){db.prepare("UPDATE services SET status='Deleted',updated_at=? WHERE id=?").run(now(),+sm[1]);return json(res,200,{ok:true})}
if(p==='/api/agents'&&method==='GET')return json(res,200,db.prepare("SELECT * FROM agents WHERE status!='Deleted' ORDER BY name").all());
if(p==='/api/agents'&&method==='POST'){let b=await parseBody(req),r=db.prepare('INSERT INTO agents(name,email,phone,image,bio,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(b.name,b.email||'',b.phone||'',b.image||'',b.bio||'',b.status||'Active',now(),now());return json(res,201,{id:Number(r.lastInsertRowid)})}
let am=p.match(/^\/api\/agents\/(\d+)$/);if(am&&method==='PUT'){let b=await parseBody(req),x=db.prepare('SELECT * FROM agents WHERE id=?').get(+am[1]);if(!x)return json(res,404,{error:'Not found'});for(const k of ['name','email','phone','image','bio','status'])if(b[k]!==undefined)x[k]=b[k];db.prepare('UPDATE agents SET name=?,email=?,phone=?,image=?,bio=?,status=?,updated_at=? WHERE id=?').run(x.name,x.email,x.phone,x.image,x.bio,x.status,now(),x.id);return json(res,200,{ok:true})}
if(am&&method==='DELETE'){db.prepare("UPDATE agents SET status='Deleted',updated_at=? WHERE id=?").run(now(),+am[1]);return json(res,200,{ok:true})}
if(p==='/api/orders'&&method==='POST'){if(!u||u.role!=='customer')return json(res,401,{error:'Please sign in to checkout'});let b=await parseBody(req),items=Array.isArray(b.items)?b.items:[];if(!items.length)return json(res,400,{error:'Cart is empty'});let total=0,valid=[];for(const it of items){let pr=db.prepare("SELECT * FROM products WHERE id=? AND status='Active'").get(+it.id);if(!pr)continue;let qty=Math.max(1,Math.min(+it.qty||1,pr.stock));total+=pr.price*qty;valid.push([pr,qty])}let no='RAL-'+Date.now(),r=db.prepare('INSERT INTO orders(customer_id,order_no,total,status,payment_method,payment_status,delivery_address,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(u.id,no,total,'Pending Payment',b.payment_method||'Mobile Money','Pending',b.delivery_address||'',now(),now());for(const [pr,qty] of valid)db.prepare('INSERT INTO order_items(order_id,product_id,name,price,qty) VALUES(?,?,?,?,?)').run(r.lastInsertRowid,pr.id,pr.name,pr.price,qty);let ref='PAY-'+Date.now();db.prepare('INSERT INTO payments(order_id,reference,method,amount,status,provider,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(r.lastInsertRowid,ref,b.payment_method||'Mobile Money',total,'Pending',process.env.PAYMENT_PROVIDER||'Provider credentials required',now(),now());return json(res,201,{id:Number(r.lastInsertRowid),order_no:no,total,payment_reference:ref,payment_status:'Pending',message:'Order created. Live MoMo/card collection activates when payment-provider credentials are configured.'})}
if(p==='/api/orders'&&method==='GET'){if(u.role==='super_admin')return json(res,200,db.prepare('SELECT * FROM orders ORDER BY created_at DESC').all());return json(res,200,db.prepare('SELECT * FROM orders WHERE customer_id=? ORDER BY created_at DESC').all(u.id))}
if(p==='/api/service-requests'&&method==='POST'){if(!u||u.role!=='customer')return json(res,401,{error:'Please sign in to request a service'});let b=await parseBody(req),r=db.prepare('INSERT INTO service_requests(customer_id,service_id,name,phone,vehicle,preferred_date,notes,status,amount,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(u.id,+b.service_id||null,b.name||u.name,b.phone||'',b.vehicle||'',b.preferred_date||'',b.notes||'','New',0,now(),now());return json(res,201,{id:Number(r.lastInsertRowid)})}
if(p==='/api/service-requests'&&method==='GET'){if(u.role==='super_admin')return json(res,200,db.prepare('SELECT r.*,s.name service_name FROM service_requests r LEFT JOIN services s ON s.id=r.service_id ORDER BY r.created_at DESC').all());return json(res,200,db.prepare('SELECT r.*,s.name service_name FROM service_requests r LEFT JOIN services s ON s.id=r.service_id WHERE r.customer_id=? ORDER BY r.created_at DESC').all(u.id))}
if(p==='/api/payments'&&method==='GET')return json(res,200,db.prepare('SELECT * FROM payments ORDER BY created_at DESC').all());
if(p==='/api/chat/conversations'&&method==='POST'){if(!u||u.role!=='customer')return json(res,401,{error:'Please sign in to chat'});let b=await parseBody(req),r=db.prepare('INSERT INTO conversations(customer_id,subject,context_type,context_id,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(u.id,b.subject||'General enquiry',b.context_type||'general',String(b.context_id||''),'Open',now(),now());return json(res,201,{id:Number(r.lastInsertRowid)})}
if(p==='/api/chat/conversations'&&method==='GET'){if(u.role==='super_admin')return json(res,200,db.prepare('SELECT c.*,u.name customer_name,u.email customer_email,(SELECT message FROM chat_messages m WHERE m.conversation_id=c.id ORDER BY id DESC LIMIT 1) last_message FROM conversations c LEFT JOIN users u ON u.id=c.customer_id ORDER BY c.updated_at DESC').all());return json(res,200,db.prepare('SELECT * FROM conversations WHERE customer_id=? ORDER BY updated_at DESC').all(u.id))}
let cm=p.match(/^\/api\/chat\/conversations\/(\d+)\/messages$/);if(cm&&method==='GET'){if(!u)return json(res,401,{error:'Sign in required'});let c=db.prepare('SELECT * FROM conversations WHERE id=?').get(+cm[1]);if(!c||!(u.role==='super_admin'||c.customer_id===u.id))return json(res,403,{error:'Forbidden'});return json(res,200,db.prepare('SELECT * FROM chat_messages WHERE conversation_id=? ORDER BY id').all(c.id))}
if(cm&&method==='POST'){let c=db.prepare('SELECT * FROM conversations WHERE id=?').get(+cm[1]);if(!c||!(u.role==='super_admin'||c.customer_id===u.id))return json(res,403,{error:'Forbidden'});let b=await parseBody(req);if(!String(b.message||'').trim())return json(res,400,{error:'Message required'});let sender=u.role==='super_admin'?'admin':'customer';let r=db.prepare('INSERT INTO chat_messages(conversation_id,sender_type,sender_id,message,created_at) VALUES(?,?,?,?,?)').run(c.id,sender,u.id,String(b.message).trim(),now());db.prepare('UPDATE conversations SET updated_at=? WHERE id=?').run(now(),c.id);return json(res,201,{id:Number(r.lastInsertRowid)})}

return json(res,404,{error:'API route not found'})}
const types={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon','.webp':'image/webp','.mp4':'video/mp4','.webm':'video/webm','.mp3':'audio/mpeg','.wav':'audio/wav','.ogg':'audio/ogg'};
const server=http.createServer(async(req,res)=>{try{let u=user(req);if(req.url.startsWith('/api/'))return await api(req,res,u);let pathname=decodeURIComponent(new URL(req.url,'http://x').pathname);if(pathname.startsWith('/uploads/')){let uf=path.join(UPLOADS,path.basename(pathname));if(fs.existsSync(uf)){res.writeHead(200,{'content-type':types[path.extname(uf)]||'application/octet-stream','cache-control':'public, max-age=86400'});return fs.createReadStream(uf).pipe(res)}}let f=path.join(PUBLIC,pathname==='/'?'index.html':pathname);if(!f.startsWith(PUBLIC))return json(res,403,{error:'Forbidden'});if(!fs.existsSync(f)||fs.statSync(f).isDirectory())f=path.join(PUBLIC,'index.html');res.writeHead(200,{'content-type':types[path.extname(f)]||'application/octet-stream','cache-control':'no-cache'});fs.createReadStream(f).pipe(res)}catch(e){console.error(e);json(res,500,{error:'Server error'})}});
server.listen(process.env.PORT||3000,()=>console.log('Revolt AutoLink running on http://localhost:'+(process.env.PORT||3000)));
