const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),{DatabaseSync}=require('node:sqlite');
const ROOT=__dirname, PUBLIC=path.join(ROOT,'public'), UPLOADS=path.join(ROOT,'uploads'), DATA=path.join(ROOT,'data');
for(const d of [PUBLIC,UPLOADS,DATA]) fs.mkdirSync(d,{recursive:true});
const db=new DatabaseSync(process.env.DATABASE_PATH||path.join(DATA,'revolt.db')); db.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;');
const schema=fs.readFileSync(path.join(ROOT,'schema.sql'),'utf8'); db.exec(schema);
db.exec(`
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY,name TEXT NOT NULL,category TEXT,description TEXT,price REAL NOT NULL DEFAULT 0,stock INTEGER NOT NULL DEFAULT 0,image TEXT,status TEXT DEFAULT 'Active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY,customer_id INTEGER REFERENCES users(id),order_no TEXT UNIQUE NOT NULL,total REAL NOT NULL DEFAULT 0,status TEXT DEFAULT 'Pending Payment',payment_method TEXT,payment_status TEXT DEFAULT 'Pending',delivery_address TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY,order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id INTEGER REFERENCES products(id),name TEXT,price REAL,qty INTEGER);
CREATE TABLE IF NOT EXISTS services(id INTEGER PRIMARY KEY,name TEXT NOT NULL,description TEXT,price_from REAL DEFAULT 0,icon TEXT,status TEXT DEFAULT 'Active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS service_requests(id INTEGER PRIMARY KEY,customer_id INTEGER REFERENCES users(id),service_id INTEGER REFERENCES services(id),name TEXT,phone TEXT,vehicle TEXT,preferred_date TEXT,notes TEXT,status TEXT DEFAULT 'New',amount REAL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS agents(id INTEGER PRIMARY KEY,name TEXT NOT NULL,email TEXT,phone TEXT,image TEXT,bio TEXT,status TEXT DEFAULT 'Active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS conversations(id INTEGER PRIMARY KEY,customer_id INTEGER REFERENCES users(id),subject TEXT,context_type TEXT,context_id TEXT,status TEXT DEFAULT 'Open',assigned_to TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS chat_messages(id INTEGER PRIMARY KEY,conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,sender_type TEXT NOT NULL,sender_id INTEGER,message TEXT NOT NULL,attachment TEXT,created_at TEXT NOT NULL,read_at TEXT);
CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY,order_id INTEGER REFERENCES orders(id),service_request_id INTEGER REFERENCES service_requests(id),reference TEXT UNIQUE,method TEXT,amount REAL,status TEXT DEFAULT 'Pending',provider TEXT DEFAULT 'Configured at hosting',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS legal_documents(id INTEGER PRIMARY KEY,title TEXT NOT NULL,category TEXT,filename TEXT,path TEXT NOT NULL,mime TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS request_links(id INTEGER PRIMARY KEY,request_type TEXT NOT NULL,request_id INTEGER NOT NULL,conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,created_at TEXT NOT NULL,UNIQUE(request_type,request_id));
CREATE TABLE IF NOT EXISTS admin_roles(id INTEGER PRIMARY KEY,name TEXT UNIQUE NOT NULL,description TEXT,permissions TEXT NOT NULL DEFAULT '[]',created_at TEXT NOT NULL);
`);
try{db.exec('ALTER TABLE vehicles ADD COLUMN old_price REAL DEFAULT 0')}catch{}
try{db.exec('ALTER TABLE alerts ADD COLUMN match_count INTEGER DEFAULT 0')}catch{}
try{db.exec('ALTER TABLE alerts ADD COLUMN last_match_vehicle_id INTEGER')}catch{}
try{db.exec("ALTER TABLE services ADD COLUMN image TEXT DEFAULT ''")}catch{}
try{db.exec("ALTER TABLE inspections ADD COLUMN customer_email TEXT DEFAULT ''")}catch{}
try{db.exec("ALTER TABLE inspections ADD COLUMN approved_date TEXT DEFAULT ''")}catch{}
try{db.exec("ALTER TABLE inspections ADD COLUMN approved_time TEXT DEFAULT ''")}catch{}
try{db.exec("ALTER TABLE inspections ADD COLUMN approved_at TEXT DEFAULT ''")}catch{}
try{db.exec("ALTER TABLE inspections ADD COLUMN approval_sent_at TEXT DEFAULT ''")}catch{}
try{db.exec("ALTER TABLE inspections ADD COLUMN approval_channel TEXT DEFAULT ''")}catch{}

try{db.prepare("INSERT OR IGNORE INTO admin_roles(name,description,permissions,created_at) VALUES(?,?,?,?)").run('Super Admin','Full platform access',JSON.stringify(['all']),new Date().toISOString())}catch{}
const now=()=>new Date().toISOString(), json=(res,code,obj)=>{res.writeHead(code,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(obj))};
const parseBody=req=>new Promise((resolve,reject)=>{let b='';req.on('data',d=>{b+=d;if(b.length>35e6)req.destroy()});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}})});
const hash=p=>{const salt=crypto.randomBytes(16).toString('hex');return salt+':'+crypto.scryptSync(p,salt,64).toString('hex')};
const verify=(p,h)=>{if(!h)return false;const [s,k]=h.split(':');return crypto.timingSafeEqual(Buffer.from(k,'hex'),crypto.scryptSync(p,s,64))};
function seed(){let n=db.prepare('SELECT count(*) n FROM users').get().n;if(!n){db.prepare('INSERT INTO users(name,email,password_hash,role,created_at) VALUES(?,?,?,?,?)').run('Revolt Administrator',process.env.ADMIN_EMAIL||'admin',hash(process.env.ADMIN_PASSWORD||'admin'),'super_admin',now())}
if(!db.prepare('SELECT count(*) n FROM vehicles').get().n){const ins=db.prepare(`INSERT INTO vehicles(title,make,model,year,price,location,mileage,transmission,fuel,engine,body_type,color,condition,status,label,description,highlights,notes,featured,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);[
['2024 Toyota Corolla LE','Toyota','Corolla',2024,185000,'Kumasi',45000,'Automatic','Petrol','1.8L','Sedan','Silver','Foreign Used','Available','VERIFIED','Clean, efficient sedan with strong everyday usability.','Low mileage|Fuel efficient|Reverse camera','Minor cosmetic wear may be present.',1],
['2023 Mercedes-Benz C300','Mercedes-Benz','C300',2023,520000,'Accra',21000,'Automatic','Petrol','2.0L','Sedan','Black','Foreign Used','Available','HOT DEAL','Premium sedan with modern comfort and technology.','Leather seats|Sunroof|Apple CarPlay','Inspection recommended before purchase.',1],
['2022 Hyundai Tucson','Hyundai','Tucson',2022,245000,'Tema',38000,'Automatic','Petrol','2.0L','SUV','White','Foreign Used','Available','NEW ARRIVAL','Practical SUV with comfortable cabin and useful technology.','Reverse camera|Parking sensors|Android Auto','Verify service records during inspection.',1],
['2021 Honda Civic Touring','Honda','Civic',2021,210000,'Accra',51000,'Automatic','Petrol','1.5L Turbo','Sedan','Blue','Foreign Used','Reserved','VERIFIED','Sporty compact sedan with premium trim.','Sunroof|Leather seats|Apple CarPlay','Currently reserved.',0],
['2023 Toyota RAV4 XLE','Toyota','RAV4',2023,385000,'Kumasi',27000,'Automatic','Hybrid','2.5L','SUV','Grey','Foreign Used','Available','GOOD VALUE','Efficient family SUV with hybrid powertrain.','Push start|Apple CarPlay|Cruise control','Confirm hybrid battery condition at inspection.',1],
['2020 Kia Sportage EX','Kia','Sportage',2020,168000,'Takoradi',68000,'Automatic','Petrol','2.4L','SUV','Red','Locally Used','Available','PRICE REDUCED','Value-focused SUV with useful comfort features.','Leather seats|Bluetooth|Reverse camera','Review maintenance history.',0]
].forEach(v=>ins.run(...v,now(),now()));}}
seed();
// Give the original demonstration vehicles a proper multi-angle gallery when they have no uploaded photography yet.
// Admin uploads always remain authoritative and can replace/set the Browse Cars display photo.
try{
 const demoMedia={
  1:[['front','https://images.unsplash.com/photo-1623869675781-80aa31012a5a?auto=format&fit=crop&w=1400&q=85'],['back','https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1400&q=85'],['interior_front','https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1400&q=85']],
  2:[['front','https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1400&q=85'],['left','https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1400&q=85'],['interior_front','https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=85']],
  3:[['front','https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1400&q=85'],['right','https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1400&q=85'],['interior_front','https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1400&q=85']],
  4:[['front','https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1400&q=85'],['left','https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1400&q=85']],
  5:[['front','https://images.unsplash.com/photo-1581540222194-0def2dda95b8?auto=format&fit=crop&w=1400&q=85'],['back','https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1400&q=85'],['interior_front','https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=85']],
  6:[['front','https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1400&q=85'],['right','https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1400&q=85'],['interior_front','https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1400&q=85']]
 };
 const add=db.prepare('INSERT INTO media(vehicle_id,type,category,path,is_primary,sort_order,created_at) VALUES(?,?,?,?,?,?,?)');
 for(const [id,items] of Object.entries(demoMedia)){
   const exists=db.prepare("SELECT count(*) n FROM media WHERE vehicle_id=? AND type='image' AND category!='360'").get(+id).n;
   if(!exists && db.prepare('SELECT id FROM vehicles WHERE id=?').get(+id)) items.forEach((x,i)=>add.run(+id,'image',x[0],x[1],i===0?1:0,i,now()));
 }
}catch(e){console.warn('Demo vehicle media seed skipped:',e.message)}

// REVOLT DEMO CATALOGUE EXPANSION: ensure the demo catalogue contains 15 public vehicles.
// This runs safely on existing Railway databases and does not duplicate titles already present.
try {
 const demoCars = [
 ['2022 Lexus RX 350','Lexus','RX 350',2022,410000,'Accra',33000,'Automatic','Petrol','3.5L','SUV','Pearl White','Foreign Used','Available','VERIFIED','Refined premium SUV with a quiet, comfortable cabin.','Leather seats|Reverse camera|Keyless entry','Demo catalogue vehicle.',1],
 ['2021 BMW X3 xDrive30i','BMW','X3',2021,365000,'Accra',44000,'Automatic','Petrol','2.0L Turbo','SUV','Black','Foreign Used','Available','PREMIUM','Compact luxury SUV with responsive performance.','Leather seats|Sunroof|Apple CarPlay','Demo catalogue vehicle.',1],
 ['2022 Ford Explorer XLT','Ford','Explorer',2022,395000,'Tema',49000,'Automatic','Petrol','2.3L Turbo','SUV','Grey','Foreign Used','Available','FAMILY SUV','Spacious three-row SUV suited to family use.','3-row seating|Reverse camera|Cruise control','Demo catalogue vehicle.',0],
 ['2020 Nissan Rogue SV','Nissan','Rogue',2020,195000,'Accra',61000,'Automatic','Petrol','2.5L','SUV','Blue','Foreign Used','Available','GOOD VALUE','Practical crossover with useful everyday features.','Push start|Bluetooth|Reverse camera','Demo catalogue vehicle.',0],
 ['2023 Honda CR-V EX','Honda','CR-V',2023,345000,'Kumasi',29000,'Automatic','Petrol','1.5L Turbo','SUV','White','Foreign Used','Available','NEW ARRIVAL','Comfortable and efficient family crossover.','Apple CarPlay|Cruise control|Reverse camera','Demo catalogue vehicle.',1],
 ['2021 Toyota Camry SE','Toyota','Camry',2021,235000,'Tema',52000,'Automatic','Petrol','2.5L','Sedan','Red','Foreign Used','Available','VERIFIED','Popular midsize sedan with sporty SE trim.','Reverse camera|Bluetooth|Cruise control','Demo catalogue vehicle.',1],
 ['2022 Hyundai Elantra SEL','Hyundai','Elantra',2022,175000,'Accra',41000,'Automatic','Petrol','2.0L','Sedan','Silver','Foreign Used','Available','GOOD VALUE','Modern compact sedan with strong fuel economy.','Apple CarPlay|Reverse camera|Keyless entry','Demo catalogue vehicle.',0],
 ['2021 Kia Sorento EX','Kia','Sorento',2021,285000,'Kumasi',56000,'Automatic','Petrol','2.5L','SUV','Dark Grey','Foreign Used','Available','FAMILY SUV','Versatile SUV with a comfortable multi-row cabin.','Leather seats|Parking sensors|Push start','Demo catalogue vehicle.',0],
 ['2023 Volkswagen Tiguan SE','Volkswagen','Tiguan',2023,315000,'Accra',26000,'Automatic','Petrol','2.0L Turbo','SUV','White','Foreign Used','Available','NEW ARRIVAL','European compact SUV with modern cabin technology.','Apple CarPlay|Digital display|Reverse camera','Demo catalogue vehicle.',1]
 ];
 const insDemo=db.prepare(`INSERT INTO vehicles(title,make,model,year,price,location,mileage,transmission,fuel,engine,body_type,color,condition,status,label,description,highlights,notes,featured,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);
 for(const v of demoCars){ if(!db.prepare('SELECT id FROM vehicles WHERE title=?').get(v[0])) insDemo.run(...v,now(),now()); }
 const galleryUrls=[
  'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1515569067071-ec3b51335dd0?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1581540222194-0def2dda95b8?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=85'
 ];
 const addMedia=db.prepare('INSERT INTO media(vehicle_id,type,category,path,is_primary,sort_order,created_at) VALUES(?,?,?,?,?,?,?)');
 demoCars.forEach((v,idx)=>{
   const car=db.prepare('SELECT id FROM vehicles WHERE title=?').get(v[0]); if(!car) return;
   const count=db.prepare("SELECT count(*) n FROM media WHERE vehicle_id=? AND type='image' AND category!='360'").get(car.id).n;
   if(!count){ const base=idx*3; ['front','back','interior_front'].forEach((cat,j)=>addMedia.run(car.id,'image',cat,galleryUrls[(base+j)%galleryUrls.length],j===0?1:0,j,now())); }
 });
}catch(e){console.warn('15-car demo catalogue expansion skipped:',e.message)}

// Populate the 15 demonstration listings with 360 frames, walkaround video and engine-start audio.
// These demo assets are only used when the corresponding media type has not already been uploaded by Admin.
try{
 const demoTitles=[
  '2024 Toyota Corolla LE','2023 Mercedes-Benz C300','2022 Hyundai Tucson','2021 Honda Civic Touring','2023 Toyota RAV4 XLE','2020 Kia Sportage EX',
  '2022 Lexus RX 350','2021 BMW X3 xDrive30i','2022 Ford Explorer XLT','2020 Nissan Rogue SV','2023 Honda CR-V EX','2021 Toyota Camry SE','2022 Hyundai Elantra SEL','2021 Kia Sorento EX','2023 Volkswagen Tiguan SE'
 ];
 const frames=[
  'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1400&q=85'
 ];
 const addDemoMedia=db.prepare('INSERT INTO media(vehicle_id,type,category,path,is_primary,sort_order,created_at) VALUES(?,?,?,?,?,?,?)');
 demoTitles.forEach((title,idx)=>{
   const car=db.prepare('SELECT id FROM vehicles WHERE title=?').get(title); if(!car)return;
   const n360=db.prepare("SELECT count(*) n FROM media WHERE vehicle_id=? AND type='image' AND category='360'").get(car.id).n;
   if(!n360){ for(let j=0;j<8;j++) addDemoMedia.run(car.id,'image','360',frames[(idx+j)%frames.length],0,100+j,now()); }
   if(!db.prepare("SELECT 1 FROM media WHERE vehicle_id=? AND type='video'").get(car.id)) addDemoMedia.run(car.id,'video','walkaround','/demo-media/walkaround-demo.mp4',0,200,now());
   if(!db.prepare("SELECT 1 FROM media WHERE vehicle_id=? AND type='audio'").get(car.id)) addDemoMedia.run(car.id,'audio','engine_sound','/demo-media/engine-start-demo.mp3',0,201,now());
 });
}catch(e){console.warn('Demo 360/video/audio population skipped:',e.message)}

if(!db.prepare("SELECT 1 FROM content_blocks WHERE key='terms'").get()) db.prepare('INSERT INTO content_blocks(key,title,subtitle,body,extra_json,updated_at) VALUES(?,?,?,?,?,?)').run('terms','Terms & Conditions','REVOLT AUTOLINK','By using Revolt AutoLink, you agree to use vehicle, store, service and communication features responsibly. Vehicle information should be independently verified during inspection. Payments, delivery and service fulfilment are subject to confirmation.', '[]', now());
if(!db.prepare('SELECT count(*) n FROM services').get().n){const q=db.prepare('INSERT INTO services(name,description,price_from,icon,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)');[['Engine Tuning','Performance diagnostics and engine tuning.',500,'⚙'],['Repairs','Mechanical and electrical repair coordination.',250,'🔧'],['Customisations','Interior, exterior and performance customisation.',500,'✨'],['General Maintenance','Routine servicing, fluids, filters and checks.',200,'🛠'],['Car Insurance','Insurance support and quotation requests.',0,'🛡'],['Vehicle Detailing','Interior and exterior detailing packages.',250,'◈']].forEach(x=>q.run(...x,'Active',now(),now()))}
if(!db.prepare('SELECT count(*) n FROM products').get().n){const q=db.prepare('INSERT INTO products(name,category,description,price,stock,image,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)');[['Premium Engine Oil','Maintenance','High quality engine oil for routine servicing.',420,20,''],['Brake Pad Set','Brakes','Front brake pad replacement set.',650,12,''],['Car Care Kit','Detailing','Wash, polish and interior care essentials.',350,25,''],['LED Headlight Pair','Lighting','Bright replacement LED headlight pair.',780,8,'']].forEach(x=>q.run(...x,'Active',now(),now()))}

// REVOLT PARTS DEMO CATALOGUE: maintain at least 15 useful store products on existing databases.
try{
 const demoProducts=[
 ['Premium Engine Oil 5W-30','Maintenance','Fully synthetic engine oil for routine servicing.',420,20,'engine-oil.svg'],
 ['Front Brake Pad Set','Brakes','Replacement front brake pad set for compatible vehicles.',650,12,'brake-pads.svg'],
 ['Car Care & Detailing Kit','Detailing','Wash, polish and interior-care essentials.',350,25,'car-care.svg'],
 ['LED Headlight Pair','Lighting','Bright replacement LED headlight pair.',780,8,'headlight.svg'],
 ['12V Car Battery','Electrical','Reliable automotive starter battery.',1250,10,'battery.svg'],
 ['Engine Air Filter','Filters','Replacement engine intake air filter.',180,30,'air-filter.svg'],
 ['Cabin Air Filter','Filters','Cabin filter for cleaner interior airflow.',160,28,'cabin-filter.svg'],
 ['Oil Filter','Filters','Spin-on engine oil filter for routine service.',95,40,'oil-filter.svg'],
 ['Spark Plug Set','Ignition','Set of four replacement spark plugs.',320,22,'spark-plugs.svg'],
 ['Wiper Blade Pair','Exterior','All-weather front windscreen wiper blades.',210,26,'wipers.svg'],
 ['Tyre Inflator 12V','Accessories','Portable 12V tyre inflator with pressure gauge.',390,16,'inflator.svg'],
 ['Car Phone Holder','Accessories','Adjustable dashboard and vent phone mount.',145,35,'phone-holder.svg'],
 ['Jumper Cable Set','Emergency','Heavy-duty booster cables for emergency starts.',280,18,'jumper-cables.svg'],
 ['Coolant 4L','Fluids','Ready-mix engine coolant for cooling-system maintenance.',190,24,'coolant.svg'],
 ['Microfibre Cleaning Towels','Detailing','Soft reusable microfibre towels for vehicle care.',120,50,'microfiber.svg']
 ];
 const q=db.prepare('INSERT INTO products(name,category,description,price,stock,image,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)');
 for(const x of demoProducts){ if(!db.prepare("SELECT id FROM products WHERE name=? AND status!='Deleted'").get(x[0])) q.run(x[0],x[1],x[2],x[3],x[4],'/demo-parts/'+x[5],'Active',now(),now()); }
}catch(e){console.warn('Demo parts population skipped:',e.message)}

if(!db.prepare("SELECT 1 FROM content_blocks WHERE key='about'").get()){db.prepare('INSERT INTO content_blocks(key,title,subtitle,body,extra_json,updated_at) VALUES(?,?,?,?,?,?)').run('about','We help you find the right car.','ABOUT REVOLT AUTOLINK','Revolt AutoLink professionally presents vehicles sourced from a growing network, helps customers compare options and coordinates inspections while keeping the vehicle at the centre of the experience.',JSON.stringify([{title:'Discover',body:'Search quality vehicle listings with useful specifications and media.'},{title:'Understand',body:'See the highlights, important notes and vehicle information before visiting.'},{title:'Inspect',body:'Request an inspection and let our team coordinate the physical visit.'},{title:'Decide',body:'Compare your shortlist and deal with the actual seller when you are ready.'}]),now())}
function token(req){let a=req.headers.authorization||'';return a.startsWith('Bearer ')?a.slice(7):''}function user(req){let t=token(req);if(!t)return null;return db.prepare('SELECT u.id,u.name,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?').get(t,now())||null}
function audit(u,action,entity,id,details=''){db.prepare('INSERT INTO audit_logs(user_id,action,entity,entity_id,details,created_at) VALUES(?,?,?,?,?,?)').run(u?.id||null,action,entity,String(id||''),details,now())}
function vehicleRows(where='1=1',params=[]){return db.prepare(`SELECT v.*, (SELECT path FROM media m WHERE m.vehicle_id=v.id AND m.type='image' AND m.category!='360' ORDER BY m.is_primary DESC,m.sort_order LIMIT 1) image, (SELECT count(*) FROM favourites f WHERE f.vehicle_id=v.id) saves, (SELECT count(*) FROM enquiries e WHERE e.vehicle_id=v.id) enquiries FROM vehicles v WHERE ${where} ORDER BY v.featured DESC,v.created_at DESC`).all(...params)}
function oauthFinish(res,provider,providerId,email,name){email=String(email||'').toLowerCase();let x=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!x){let r=db.prepare('INSERT INTO users(name,email,password_hash,role,created_at) VALUES(?,?,?,?,?)').run(name,email,hash(crypto.randomBytes(32).toString('hex')),'customer',now());x=db.prepare('SELECT * FROM users WHERE id=?').get(r.lastInsertRowid);db.prepare('INSERT OR IGNORE INTO customers(name,phone,email,created_at) VALUES(?,?,?,?)').run(name,'',email,now())}db.prepare('INSERT INTO oauth_accounts(user_id,provider,provider_id,created_at) VALUES(?,?,?,?) ON CONFLICT(provider,provider_id) DO UPDATE SET user_id=excluded.user_id').run(x.id,provider,providerId,now());let t=crypto.randomBytes(32).toString('hex'),exp=new Date(Date.now()+30*864e5).toISOString();db.prepare('INSERT INTO sessions(token,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(t,x.id,exp,now());let payload=Buffer.from(JSON.stringify({token:t,user:{id:x.id,name:x.name,email:x.email,phone:'',role:'customer'}})).toString('base64url');res.writeHead(302,{location:'/?oauth='+payload+'#account'});res.end()}

function setting(k,def=''){let x=db.prepare('SELECT value FROM settings WHERE key=?').get(k);return x?.value||def}
function setSetting(k,v){db.prepare('INSERT INTO settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').run(k,String(v||''),now())}
function normalizeWa(n){let x=String(n||'').replace(/\D/g,'');if(x.startsWith('0'))x='233'+x.slice(1);return x}
async function sendEmail(to,subject,body,html=''){let key=process.env.RESEND_API_KEY||setting('resend_api_key');if(!key||!to)return {skipped:true};let from=process.env.NOTIFY_FROM_EMAIL||setting('from_email','Revolt AutoLink <onboarding@resend.dev>');try{let payload={from,to:[to],subject,text:body};if(html)payload.html=html;let r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:'Bearer '+key,'content-type':'application/json'},body:JSON.stringify(payload)});return {ok:r.ok,status:r.status}}catch(e){return {ok:false,error:e.message}}}
async function sendWhatsApp(to,body){let token=process.env.WHATSAPP_TOKEN||setting('whatsapp_token'),pid=process.env.WHATSAPP_PHONE_NUMBER_ID||setting('whatsapp_phone_number_id'),n=normalizeWa(to);if(!token||!pid||!n)return {skipped:true};try{let r=await fetch(`https://graph.facebook.com/v23.0/${pid}/messages`,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:n,type:'text',text:{body}})});return {ok:r.ok}}catch(e){return {ok:false}}}
async function notifyRequest(user,kind,id,summary){let adminEmail=process.env.ADMIN_NOTIFY_EMAIL||setting('admin_notify_email'),adminWa=process.env.ADMIN_NOTIFY_WHATSAPP||setting('admin_notify_whatsapp','0500081646'),customerEmail=user?.email||'',c=db.prepare('SELECT phone FROM customers WHERE email=?').get(customerEmail),customerWa=c?.phone||'';let msg=`Revolt AutoLink: ${kind} #${id} received. ${summary||''}`.trim();Promise.allSettled([sendEmail(customerEmail,`Revolt AutoLink - ${kind} received`,msg),sendWhatsApp(customerWa,msg),sendEmail(adminEmail,`New Revolt AutoLink ${kind} #${id}`,msg),sendWhatsApp(adminWa,`ADMIN: ${msg}`)]).catch(()=>{})}
function inspectionApprovalTemplate(x){let date=x.approved_date||x.preferred_date||'',time=x.approved_time||x.preferred_time||'',title=x.vehicle_title||'your selected vehicle';let text=`Hello ${x.name}, thank you for choosing Revolt AutoLink. Your inspection for ${title} has been approved. Date: ${date}. Time: ${time}. We appreciate your request and look forward to assisting you. If you need to make a change, reply through your Revolt AutoLink chat or contact our team. Find It. Trust It. Drive It.`;let html=`<div style="font-family:Arial,sans-serif;background:#f5f6f8;padding:28px;color:#111827"><div style="max-width:620px;margin:auto;background:#fff;border-radius:16px;overflow:hidden;border:1px solid #e5e7eb"><div style="background:#111827;color:white;padding:24px 28px;border-bottom:4px solid #e11d2e"><div style="font-size:13px;color:#fb7185;font-weight:700;letter-spacing:.08em">REVOLT AUTOLINK</div><h2 style="margin:7px 0 0">Inspection Confirmed</h2></div><div style="padding:28px"><p>Hello <b>${x.name}</b>,</p><p>Thank you for choosing Revolt AutoLink. Your vehicle inspection has been approved and scheduled as follows:</p><div style="background:#f8fafc;border-left:4px solid #e11d2e;padding:18px;margin:22px 0;border-radius:8px"><div style="font-size:17px;font-weight:700;margin-bottom:10px">${title}</div><div>📅 Date: <b>${date}</b></div><div style="margin-top:8px">🕒 Time: <b>${time}</b></div></div><p>We appreciate your request and look forward to assisting you. Please arrive on time. If you need to make a change, reply through your Revolt AutoLink chat or contact our team.</p><p style="margin-top:26px">Thank you,<br><b>Revolt AutoLink Team</b></p><p style="margin-top:24px;color:#6b7280;font-size:13px"><b>Find It. Trust It. Drive It.</b></p></div></div></div>`;return {text,html,date,time,title}}
async function sendInspectionApproval(x){let t=inspectionApprovalTemplate(x),channel=String(x.contact_method||'Email').toLowerCase(),results={};if(channel.includes('email'))results.email=await sendEmail(x.customer_email||'',`Inspection Approved - ${t.title}`,t.text,t.html);if(channel.includes('whatsapp'))results.whatsapp=await sendWhatsApp(x.phone,t.text);return {channel:x.contact_method,results,...t}}
function requestConversation(user,kind,id,subject,initial){if(!user||user.role!=='customer')return null;let r=db.prepare('INSERT INTO conversations(customer_id,subject,context_type,context_id,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(user.id,subject,kind,String(id),'Open',now(),now());let cid=Number(r.lastInsertRowid);db.prepare('INSERT OR IGNORE INTO request_links(request_type,request_id,conversation_id,created_at) VALUES(?,?,?,?)').run(kind,id,cid,now());db.prepare('INSERT INTO chat_messages(conversation_id,sender_type,sender_id,message,created_at) VALUES(?,?,?,?,?)').run(cid,'system',null,initial,now());return cid}
function saveDataFile(data,name,prefix='file'){let m=String(data||'').match(/^data:([^;]+);base64,(.+)$/);if(!m)throw Error('Invalid file');let ext=(String(name||'').split('.').pop()||'bin').replace(/[^a-z0-9]/gi,'').toLowerCase(),fn=`${prefix}-${Date.now()}-${crypto.randomBytes(3).toString('hex')}.${ext}`,fp=path.join(UPLOADS,fn);fs.writeFileSync(fp,Buffer.from(m[2],'base64'));return {path:'/uploads/'+fn,mime:m[1],filename:name||fn}}

async function api(req,res,u){let url=new URL(req.url,'http://x'),p=url.pathname,method=req.method;
if(p==='/api/health')return json(res,200,{ok:true,time:now()});

if(p==='/api/admin/notification-settings'&&method==='GET')return json(res,200,{admin_notify_email:setting('admin_notify_email'),admin_notify_whatsapp:setting('admin_notify_whatsapp','0500081646'),from_email:setting('from_email'),resend_configured:!!(process.env.RESEND_API_KEY||setting('resend_api_key')),whatsapp_configured:!!((process.env.WHATSAPP_TOKEN||setting('whatsapp_token'))&&(process.env.WHATSAPP_PHONE_NUMBER_ID||setting('whatsapp_phone_number_id')))});
if(p==='/api/admin/payment-settings'&&method==='GET')return json(res,200,{provider:setting('payment_provider','Paystack'),currency:setting('payment_currency','GHS'),public_key:setting('paystack_public_key'),secret_configured:!!(process.env.PAYSTACK_SECRET_KEY||setting('paystack_secret_key')),callback_url:setting('payment_callback_url',process.env.APP_URL?process.env.APP_URL+'/#account':'')});
if(p==='/api/admin/payment-settings'&&method==='PUT'){let b=await parseBody(req);for(const k of ['payment_provider','payment_currency','paystack_public_key','paystack_secret_key','payment_callback_url'])if(b[k]!==undefined&&b[k]!=='••••••••')setSetting(k,b[k]);return json(res,200,{ok:true})}
if(p==='/api/request-chat'&&method==='GET'){if(!u)return json(res,401,{error:'Sign in required'});let type=url.searchParams.get('type'),id=+url.searchParams.get('id'),x=db.prepare('SELECT conversation_id FROM request_links WHERE request_type=? AND request_id=?').get(type,id);if(!x)return json(res,404,{error:'No linked chat'});let c=db.prepare('SELECT * FROM conversations WHERE id=?').get(x.conversation_id);if(u.role!=='super_admin'&&c.customer_id!==u.id)return json(res,403,{error:'Forbidden'});return json(res,200,{conversation_id:x.conversation_id})}
if(p==='/api/admin/notification-settings'&&method==='PUT'){let b=await parseBody(req);for(const k of ['admin_notify_email','admin_notify_whatsapp','from_email','resend_api_key','whatsapp_token','whatsapp_phone_number_id'])if(b[k]!==undefined&&b[k]!=='••••••••')setSetting(k,b[k]);return json(res,200,{ok:true})}
if(p==='/api/admin/upload'&&method==='POST'){let b=await parseBody(req),f=saveDataFile(b.data,b.name,'admin');return json(res,201,f)}
if(p==='/api/legal-documents'&&method==='GET')return json(res,200,db.prepare('SELECT * FROM legal_documents ORDER BY created_at DESC').all());
if(p==='/api/legal-documents'&&method==='POST'){let b=await parseBody(req),f=saveDataFile(b.data,b.name,'legal'),r=db.prepare('INSERT INTO legal_documents(title,category,filename,path,mime,created_at) VALUES(?,?,?,?,?,?)').run(b.title||b.name,b.category||'Agreement',f.filename,f.path,f.mime,now());return json(res,201,{id:Number(r.lastInsertRowid),...f})}
let ldm=p.match(/^\/api\/legal-documents\/(\d+)$/);if(ldm&&method==='DELETE'){let x=db.prepare('SELECT * FROM legal_documents WHERE id=?').get(+ldm[1]);if(x){try{fs.unlinkSync(path.join(ROOT,x.path.replace(/^\//,'')))}catch{}db.prepare('DELETE FROM legal_documents WHERE id=?').run(x.id)}return json(res,200,{ok:true})}

if(p==='/api/auth/admin-reset'&&method==='POST'){let b=await parseBody(req),resetKey=process.env.ADMIN_RESET_KEY||'';if(!resetKey)return json(res,503,{error:'Admin login reset is not enabled. Set ADMIN_RESET_KEY in Railway Variables first.'});if(!b.reset_key||!crypto.timingSafeEqual(crypto.createHash('sha256').update(String(b.reset_key)).digest(),crypto.createHash('sha256').update(resetKey).digest()))return json(res,403,{error:'Invalid reset key'});let login=String(b.email||'admin').trim(),x=db.prepare("SELECT * FROM users WHERE (email=? OR name=?) AND role!='customer'").get(login.toLowerCase(),login);if(!x)return json(res,404,{error:'Admin account not found'});if(String(b.password||'').length<8)return json(res,400,{error:'New password must be at least 8 characters'});db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(hash(String(b.password)),x.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(x.id);return json(res,200,{ok:true,message:'Admin password reset. Sign in with the new password.'})}
if(p==='/api/admin/notifications'&&method==='GET'){if(!u||u.role==='customer')return json(res,401,{error:'Admin login required'});let since=setting('admin_notification_seen_at','1970-01-01T00:00:00.000Z');let one=(table,extra='')=>db.prepare(`SELECT count(*) n FROM ${table} WHERE created_at>? ${extra}`).get(since).n;let counts={enquiries:one('enquiries'),inspections:one('inspections'),car_requests:one('car_requests'),contacts:one('contact_messages'),service_requests:one('service_requests'),orders:one('orders'),chats:db.prepare("SELECT count(*) n FROM chat_messages WHERE created_at>? AND sender_type='customer'").get(since).n};counts.total=Object.values(counts).reduce((a,b)=>a+Number(b||0),0);return json(res,200,{since,counts})}
if(p==='/api/admin/notifications/read'&&method==='POST'){if(!u||u.role==='customer')return json(res,401,{error:'Admin login required'});setSetting('admin_notification_seen_at',now());return json(res,200,{ok:true})}
if(p==='/api/auth/login'&&method==='POST'){let b=await parseBody(req),x=db.prepare('SELECT * FROM users WHERE (email=? OR name=?) AND active=1').get((b.email||'').toLowerCase(),(b.email||'').trim());if(!x||!verify(b.password||'',x.password_hash))return json(res,401,{error:'Invalid email or password'});let t=crypto.randomBytes(32).toString('hex'),exp=new Date(Date.now()+7*864e5).toISOString();db.prepare('INSERT INTO sessions(token,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(t,x.id,exp,now());audit(x,'login','session',t);return json(res,200,{token:t,user:{id:x.id,name:x.name,email:x.email,role:x.role}})}
if(p==='/api/auth/me')return u?json(res,200,u):json(res,401,{error:'Unauthorized'});
const adminProtected=(p==='/api/analytics/dashboard'||p==='/api/audit'||p==='/api/customers'||(p==='/api/vehicles'&&method==='POST')||(p==='/api/vehicles'&&method==='GET'&&url.searchParams.get('admin')==='1')||(/^\/api\/vehicles\/\d+$/.test(p)&&['PUT','DELETE'].includes(method))||(['/api/enquiries','/api/inspections','/api/alerts','/api/contact','/api/car-requests'].includes(p)&&method==='GET')||((p==='/api/content/about'||p==='/api/content/terms')&&method==='PUT')||(p==='/api/payments'&&method==='GET')||(['/api/admin/notification-settings','/api/admin/payment-settings','/api/admin/upload','/api/legal-documents'].includes(p)&&method!=='GET')||(['/api/admin/notification-settings','/api/admin/payment-settings'].includes(p)&&method==='GET')||(/^\/api\/(products|services|agents)\/\d+$/.test(p)&&['PUT','DELETE'].includes(method))||(['/api/products','/api/services','/api/agents'].includes(p)&&method==='POST')||(/^\/api\/chat\/conversations\/\d+\/messages$/.test(p)&&method==='POST')||(/^\/api\/vehicles\/\d+\/media$/.test(p)&&method==='POST')||(/^\/api\/media\/\d+$/.test(p)&&['DELETE','PUT'].includes(method))||(/^\/api\/legal-documents\/\d+$/.test(p)&&method==='DELETE'));if(adminProtected&&(!u||u.role==='customer'))return json(res,401,{error:'Admin login required'});
if(p==='/api/oauth/config'&&method==='GET')return json(res,200,{google:!!(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET),facebook:!!(process.env.FACEBOOK_APP_ID&&process.env.FACEBOOK_APP_SECRET)});
if(p==='/api/oauth/google'&&method==='GET'){if(!process.env.GOOGLE_CLIENT_ID)return json(res,503,{error:'Google sign-in is not configured'});let base=process.env.APP_URL||(`${req.headers['x-forwarded-proto']||'http'}://${req.headers.host}`),redirect=base+'/api/oauth/google/callback',state=crypto.randomBytes(16).toString('hex');db.prepare('INSERT INTO oauth_states(state,provider,created_at) VALUES(?,?,?)').run(state,'google',now());res.writeHead(302,{location:'https://accounts.google.com/o/oauth2/v2/auth?'+new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:redirect,response_type:'code',scope:'openid email profile',state,prompt:'select_account'}).toString()});return res.end()}
if(p==='/api/oauth/google/callback'&&method==='GET'){let state=url.searchParams.get('state'),code=url.searchParams.get('code'),st=db.prepare("SELECT * FROM oauth_states WHERE state=? AND provider='google'").get(state);if(!st||!code)return json(res,400,{error:'Invalid OAuth response'});db.prepare('DELETE FROM oauth_states WHERE state=?').run(state);let base=process.env.APP_URL||(`${req.headers['x-forwarded-proto']||'http'}://${req.headers.host}`),redirect=base+'/api/oauth/google/callback';let tr=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:redirect,grant_type:'authorization_code'})}),td=await tr.json();if(!td.access_token)return json(res,401,{error:'Google sign-in failed'});let pr=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{authorization:'Bearer '+td.access_token}}),profile=await pr.json();return oauthFinish(res,'google',profile.sub,profile.email,profile.name||profile.email)}
if(p==='/api/oauth/facebook'&&method==='GET'){if(!process.env.FACEBOOK_APP_ID)return json(res,503,{error:'Facebook sign-in is not configured'});let base=process.env.APP_URL||(`${req.headers['x-forwarded-proto']||'http'}://${req.headers.host}`),redirect=base+'/api/oauth/facebook/callback',state=crypto.randomBytes(16).toString('hex');db.prepare('INSERT INTO oauth_states(state,provider,created_at) VALUES(?,?,?)').run(state,'facebook',now());res.writeHead(302,{location:'https://www.facebook.com/v23.0/dialog/oauth?'+new URLSearchParams({client_id:process.env.FACEBOOK_APP_ID,redirect_uri:redirect,state,scope:'email,public_profile'}).toString()});return res.end()}
if(p==='/api/oauth/facebook/callback'&&method==='GET'){let state=url.searchParams.get('state'),code=url.searchParams.get('code'),st=db.prepare("SELECT * FROM oauth_states WHERE state=? AND provider='facebook'").get(state);if(!st||!code)return json(res,400,{error:'Invalid OAuth response'});db.prepare('DELETE FROM oauth_states WHERE state=?').run(state);let base=process.env.APP_URL||(`${req.headers['x-forwarded-proto']||'http'}://${req.headers.host}`),redirect=base+'/api/oauth/facebook/callback';let tr=await fetch('https://graph.facebook.com/v23.0/oauth/access_token?'+new URLSearchParams({client_id:process.env.FACEBOOK_APP_ID,client_secret:process.env.FACEBOOK_APP_SECRET,redirect_uri:redirect,code})),td=await tr.json();if(!td.access_token)return json(res,401,{error:'Facebook sign-in failed'});let pr=await fetch('https://graph.facebook.com/me?'+new URLSearchParams({fields:'id,name,email',access_token:td.access_token})),profile=await pr.json();return oauthFinish(res,'facebook',profile.id,profile.email||`facebook-${profile.id}@revoltautolink.local`,profile.name||'Facebook User')}
if(p==='/api/customer/register'&&method==='POST'){let b=await parseBody(req),email=(b.email||'').trim().toLowerCase();if(!b.name||!email||!b.password)return json(res,400,{error:'Name, email and password are required'});if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return json(res,409,{error:'An account with this email already exists'});let r=db.prepare('INSERT INTO users(name,email,password_hash,role,created_at) VALUES(?,?,?,?,?)').run(b.name,email,hash(b.password),'customer',now());let t=crypto.randomBytes(32).toString('hex'),exp=new Date(Date.now()+30*864e5).toISOString();db.prepare('INSERT INTO sessions(token,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(t,r.lastInsertRowid,exp,now());db.prepare('INSERT OR IGNORE INTO customers(name,phone,email,created_at) VALUES(?,?,?,?)').run(b.name,b.phone||'',email,now());return json(res,201,{token:t,user:{id:Number(r.lastInsertRowid),name:b.name,email,phone:b.phone||'',role:'customer'}})}
if(p==='/api/customer/login'&&method==='POST'){let b=await parseBody(req),x=db.prepare("SELECT * FROM users WHERE email=? AND role='customer' AND active=1").get((b.email||'').trim().toLowerCase());if(!x||!verify(b.password||'',x.password_hash))return json(res,401,{error:'Invalid email or password'});let t=crypto.randomBytes(32).toString('hex'),exp=new Date(Date.now()+30*864e5).toISOString();db.prepare('INSERT INTO sessions(token,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(t,x.id,exp,now());let c=db.prepare('SELECT phone FROM customers WHERE email=?').get(x.email);return json(res,200,{token:t,user:{id:x.id,name:x.name,email:x.email,phone:c?.phone||'',role:x.role}})}
if(p==='/api/customer/profile'&&method==='GET'){if(!u||u.role!=='customer')return json(res,401,{error:'Unauthorized'});let c=db.prepare('SELECT phone FROM customers WHERE email=?').get(u.email);return json(res,200,{...u,phone:c?.phone||''})}
if(p==='/api/customer/profile'&&method==='PUT'){if(!u||u.role!=='customer')return json(res,401,{error:'Unauthorized'});let b=await parseBody(req);db.prepare('UPDATE users SET name=? WHERE id=?').run(b.name||u.name,u.id);db.prepare('INSERT INTO customers(name,phone,email,created_at) VALUES(?,?,?,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,phone=excluded.phone').run(b.name||u.name,b.phone||'',u.email,now());return json(res,200,{id:u.id,name:b.name||u.name,email:u.email,phone:b.phone||'',role:u.role})}
if(p==='/api/vehicles'&&method==='GET'){let q=url.searchParams.get('q')||'',status=url.searchParams.get('status')||'Available',admin=url.searchParams.get('admin')==='1';let w=admin?'1=1':"TRIM(LOWER(status)) IN ('available','reserved','sold')",params=[];if(q){w+=' AND (title LIKE ? OR make LIKE ? OR model LIKE ? OR location LIKE ?)';params.push(...Array(4).fill('%'+q+'%'))}return json(res,200,vehicleRows(w,params))}
let vm=p.match(/^\/api\/vehicles\/(\d+)$/);if(vm&&method==='GET'){let v=vehicleRows('v.id=?',[+vm[1]])[0];if(!v)return json(res,404,{error:'Not found'});db.prepare('UPDATE vehicles SET views=views+1 WHERE id=?').run(v.id);v.media=db.prepare('SELECT * FROM media WHERE vehicle_id=? ORDER BY sort_order').all(v.id);return json(res,200,v)}
if(p==='/api/vehicles'&&method==='POST'){let b=await parseBody(req);let r=db.prepare(`INSERT INTO vehicles(title,make,model,year,price,location,mileage,transmission,fuel,engine,body_type,color,condition,status,label,description,highlights,notes,featured,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(b.title||'',b.make||'',b.model||'',+b.year||0,+b.price||0,b.location||'',+b.mileage||0,b.transmission||'',b.fuel||'',b.engine||'',b.body_type||'',b.color||'',b.condition||'',(b.status&&String(b.status).trim())||'Available',b.label||'',b.description||'',b.highlights||'',b.notes||'',b.featured?1:0,now(),now());audit(u,'create','vehicle',r.lastInsertRowid,b.title);refreshSmartAlertMatches(Number(r.lastInsertRowid));return json(res,201,{id:Number(r.lastInsertRowid)})}
if(vm&&method==='PUT'){let b=await parseBody(req),id=+vm[1];let old=db.prepare('SELECT * FROM vehicles WHERE id=?').get(id);if(!old)return json(res,404,{error:'Not found'});let keys=['title','make','model','year','price','location','mileage','transmission','fuel','engine','body_type','color','condition','status','label','description','highlights','notes','featured'];for(let k of keys)if(b[k]!==undefined)old[k]=b[k];db.prepare(`UPDATE vehicles SET title=?,make=?,model=?,year=?,price=?,location=?,mileage=?,transmission=?,fuel=?,engine=?,body_type=?,color=?,condition=?,status=?,label=?,description=?,highlights=?,notes=?,featured=?,updated_at=? WHERE id=?`).run(...keys.map(k=>old[k]),now(),id);audit(u,'update','vehicle',id);refreshSmartAlertMatches(id);return json(res,200,{ok:true})}
if(vm&&method==='DELETE'){db.prepare('DELETE FROM vehicles WHERE id=?').run(+vm[1]);audit(u,'delete','vehicle',+vm[1]);return json(res,200,{ok:true})}
if(p==='/api/enquiries'&&method==='POST'){if(!u||u.role!=='customer')return json(res,401,{error:'Please sign in before making an enquiry'});let b=await parseBody(req);let r=db.prepare('INSERT INTO enquiries(vehicle_id,name,phone,email,contact_method,message,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(b.vehicle_id||null,b.name,b.phone,b.email||u.email,b.contact_method||'WhatsApp',b.message||'','New',now(),now()),id=Number(r.lastInsertRowid),cid=requestConversation(u,'enquiry',id,'Vehicle enquiry #'+id,'Your vehicle enquiry has been received. Reply here and the Revolt team will respond.');notifyRequest(u,'vehicle enquiry',id,b.message);return json(res,201,{id,conversation_id:cid})}
if(p==='/api/enquiries'&&method==='GET'){return json(res,200,db.prepare('SELECT e.*,v.title vehicle_title FROM enquiries e LEFT JOIN vehicles v ON v.id=e.vehicle_id ORDER BY e.created_at DESC').all())}
if(p==='/api/inspections'&&method==='POST'){if(!u||u.role!=='customer')return json(res,401,{error:'Please sign in before requesting an inspection'});let b=await parseBody(req);let r=db.prepare('INSERT INTO inspections(vehicle_id,name,phone,preferred_date,preferred_time,contact_method,notes,status,created_at,updated_at,customer_email) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(b.vehicle_id,b.name,b.phone,b.preferred_date,b.preferred_time,b.contact_method||'WhatsApp',b.notes||'','Pending',now(),now(),u.email||''),id=Number(r.lastInsertRowid),cid=requestConversation(u,'inspection',id,'Inspection request #'+id,'Your inspection request has been received. Use this chat for updates and questions.');notifyRequest(u,'inspection request',id,b.notes);return json(res,201,{id,conversation_id:cid})}
if(p==='/api/inspections'&&method==='GET'){return json(res,200,db.prepare('SELECT i.*,v.title vehicle_title FROM inspections i JOIN vehicles v ON v.id=i.vehicle_id ORDER BY i.created_at DESC').all())}
if(p==='/api/alerts'&&method==='POST'){let b=await parseBody(req);let criteria=JSON.stringify({query:b.query||'',make:b.make||'',model:b.model||'',budget:+b.budget||0,location:b.location||'',notes:b.notes||''});let r=db.prepare('INSERT INTO alerts(name,phone,email,criteria,status,created_at) VALUES(?,?,?,?,?,?)').run(b.name||'',b.phone||'',b.email||'',criteria,'Active',now());return json(res,201,{id:Number(r.lastInsertRowid)})}
if(p==='/api/alerts'&&method==='GET'){return json(res,200,db.prepare('SELECT a.*,v.title match_vehicle_title FROM alerts a LEFT JOIN vehicles v ON v.id=a.last_match_vehicle_id ORDER BY a.created_at DESC').all())}
if(p==='/api/contact'&&method==='POST'){let b=await parseBody(req);let r=db.prepare('INSERT INTO contact_messages(name,phone,email,message,status,created_at) VALUES(?,?,?,?,?,?)').run(b.name,b.phone||'',b.email||'',b.message,'New',now());return json(res,201,{id:Number(r.lastInsertRowid)})}
if(p==='/api/contact'&&method==='GET'){return json(res,200,db.prepare('SELECT * FROM contact_messages ORDER BY created_at DESC').all())}
if(p==='/api/car-requests'&&method==='GET'){return json(res,200,db.prepare('SELECT * FROM car_requests ORDER BY created_at DESC').all())}
if(p==='/api/car-requests'&&method==='POST'){if(!u||u.role!=='customer')return json(res,401,{error:'Please sign in before making a request'});let b=await parseBody(req);let r=db.prepare('INSERT INTO car_requests(name,phone,make,model,budget,body_type,transmission,condition,notes,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(b.name,b.phone,b.make||'',b.model||'',+b.budget||0,b.body_type||'',b.transmission||'',b.condition||'',b.notes||'','New',now()),id=Number(r.lastInsertRowid),cid=requestConversation(u,'car_request',id,'Find a Car request #'+id,'We received your vehicle sourcing request. Our team can continue the conversation here.');notifyRequest(u,'Find a Car request',id,`${b.make||''} ${b.model||''}`);return json(res,201,{id,conversation_id:cid})}
if(p==='/api/customers'&&method==='GET'){return json(res,200,db.prepare('SELECT c.*, (SELECT count(*) FROM enquiries e WHERE e.email=c.email OR e.phone=c.phone) enquiries FROM customers c ORDER BY c.created_at DESC').all())}
let em=p.match(/^\/api\/enquiries\/(\d+)\/status$/);if(em&&method==='PUT'){let b=await parseBody(req);db.prepare('UPDATE enquiries SET status=?,updated_at=? WHERE id=?').run(b.status||'New',now(),+em[1]);return json(res,200,{ok:true})}
let ia=p.match(/^\/api\/inspections\/(\d+)\/approve$/);if(ia&&method==='POST'){if(!u||u.role==='customer')return json(res,401,{error:'Admin login required'});let id=+ia[1],b=await parseBody(req),x=db.prepare('SELECT i.*,v.title vehicle_title FROM inspections i JOIN vehicles v ON v.id=i.vehicle_id WHERE i.id=?').get(id);if(!x)return json(res,404,{error:'Inspection request not found'});let ad=b.approved_date||x.preferred_date,at=b.approved_time||x.preferred_time;if(!ad||!at)return json(res,400,{error:'Approved date and time are required'});db.prepare("UPDATE inspections SET approved_date=?,approved_time=?,status='Approved',approved_at=?,approval_channel=?,updated_at=? WHERE id=?").run(ad,at,now(),x.contact_method||'Email',now(),id);x={...x,approved_date:ad,approved_time:at,status:'Approved'};let delivery=await sendInspectionApproval(x);let successful=Object.values(delivery.results||{}).some(r=>r&&r.ok);if(successful)db.prepare('UPDATE inspections SET approval_sent_at=? WHERE id=?').run(now(),id);let link=db.prepare("SELECT conversation_id FROM request_links WHERE request_type='inspection' AND request_id=?").get(id);if(link){db.prepare('INSERT INTO chat_messages(conversation_id,sender_type,sender_id,message,created_at) VALUES(?,?,?,?,?)').run(link.conversation_id,'system',u.id,`Inspection approved for ${ad} at ${at}. Confirmation sent via ${x.contact_method}.`,now());db.prepare('UPDATE conversations SET updated_at=? WHERE id=?').run(now(),link.conversation_id)}audit(u,'approve','inspection',id,`${ad} ${at} via ${x.contact_method}`);return json(res,200,{ok:true,delivery,sent:successful})}
let im=p.match(/^\/api\/inspections\/(\d+)\/status$/);if(im&&method==='PUT'){let b=await parseBody(req);db.prepare('UPDATE inspections SET status=?,updated_at=? WHERE id=?').run(b.status||'Pending',now(),+im[1]);return json(res,200,{ok:true})}
if(p==='/api/content/about'&&method==='GET'){let x=db.prepare("SELECT * FROM content_blocks WHERE key='about'").get();if(!x)return json(res,404,{error:'About content not found'});try{x.items=JSON.parse(x.extra_json||'[]')}catch{x.items=[]}return json(res,200,x)}
if((p==='/api/content/about'||p==='/api/content/terms')&&method==='PUT'){let b=await parseBody(req);let extra=JSON.stringify(Array.isArray(b.items)?b.items:[]);db.prepare("INSERT INTO content_blocks(key,title,subtitle,body,extra_json,updated_at) VALUES('about',?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET title=excluded.title,subtitle=excluded.subtitle,body=excluded.body,extra_json=excluded.extra_json,updated_at=excluded.updated_at").run(b.title||'',b.subtitle||'',b.body||'',extra,now());audit(u,'update','content','about');return json(res,200,{ok:true})}
let mm=p.match(/^\/api\/vehicles\/(\d+)\/media$/);if(mm&&method==='POST'){let b=await parseBody(req),id=+mm[1];if(!db.prepare('SELECT id FROM vehicles WHERE id=?').get(id))return json(res,404,{error:'Vehicle not found'});let files=Array.isArray(b.files)?b.files:[];if(!files.length)return json(res,400,{error:'No media supplied'});let current=db.prepare('SELECT count(*) n FROM media WHERE vehicle_id=?').get(id).n,currentImages=db.prepare("SELECT count(*) n FROM media WHERE vehicle_id=? AND type='image' AND category!='360'").get(id).n,saved=[];for(let i=0;i<files.length;i++){let f=files[i]||{},m=String(f.data||'').match(/^data:(image\/(?:jpeg|png|webp)|video\/(?:mp4|webm)|audio\/(?:mpeg|mp3|wav|ogg));base64,(.+)$/);if(!m)continue;let mime=m[1],type=mime.startsWith('image/')?'image':mime.startsWith('video/')?'video':'audio',ext=mime.includes('png')?'png':mime.includes('webp')?'webp':mime.includes('webm')?'webm':mime.includes('wav')?'wav':mime.includes('ogg')?'ogg':mime.includes('mpeg')||mime.includes('mp3')?'mp3':mime.includes('mp4')?'mp4':'jpg',buf=Buffer.from(m[2],'base64'),limit=type==='image'?8*1024*1024:60*1024*1024;if(buf.length>limit)continue;let name=`vehicle-${id}-${Date.now()}-${i}.${ext}`,disk=path.join(UPLOADS,name);fs.writeFileSync(disk,buf);let publicPath='/uploads/'+name;if(type==='image'&&f.is_primary===true)db.prepare("UPDATE media SET is_primary=0 WHERE vehicle_id=? AND type='image'").run(id);let r=db.prepare('INSERT INTO media(vehicle_id,type,category,path,is_primary,sort_order,created_at) VALUES(?,?,?,?,?,?,?)').run(id,type,f.category||type,publicPath,(type==='image'&&f.category!=='360'&&(f.is_primary===true||(currentImages===0&&!saved.some(x=>x.type==='image'&&x.category!=='360'))))?1:0,current+i,now());saved.push({id:Number(r.lastInsertRowid),path:publicPath,type,category:f.category||type})}audit(u,'upload','vehicle_media',id,`${saved.length} media file(s)`);return json(res,201,{files:saved})}
let md=p.match(/^\/api\/media\/(\d+)$/);if(md&&method==='PUT'){let m=db.prepare('SELECT * FROM media WHERE id=?').get(+md[1]);if(!m)return json(res,404,{error:'Media not found'});let b=await parseBody(req);if(b.is_primary){db.prepare("UPDATE media SET is_primary=0 WHERE vehicle_id=? AND type='image'").run(m.vehicle_id);db.prepare('UPDATE media SET is_primary=1 WHERE id=?').run(m.id)}if(b.category)db.prepare('UPDATE media SET category=? WHERE id=?').run(b.category,m.id);return json(res,200,{ok:true})}if(md&&method==='DELETE'){let m=db.prepare('SELECT * FROM media WHERE id=?').get(+md[1]);if(!m)return json(res,404,{error:'Media not found'});if(m.path&&m.path.startsWith('/uploads/')){let f=path.join(UPLOADS,path.basename(m.path));try{fs.unlinkSync(f)}catch{}}db.prepare('DELETE FROM media WHERE id=?').run(+md[1]);return json(res,200,{ok:true})}

if(p==='/api/admin/roles'&&method==='GET'){if(!u||u.role==='customer')return json(res,401,{error:'Admin login required'});return json(res,200,db.prepare('SELECT * FROM admin_roles ORDER BY name').all().map(x=>({...x,permissions:JSON.parse(x.permissions||'[]')})))}
if(p==='/api/admin/roles'&&method==='POST'){if(!u||u.role!=='super_admin')return json(res,403,{error:'Super Admin required'});let b=await parseBody(req);if(!b.name)return json(res,400,{error:'Role name required'});let r=db.prepare('INSERT INTO admin_roles(name,description,permissions,created_at) VALUES(?,?,?,?)').run(b.name,b.description||'',JSON.stringify(b.permissions||[]),now());return json(res,201,{id:Number(r.lastInsertRowid)})}
let rr=p.match(/^\/api\/admin\/roles\/(\d+)$/);if(rr&&method==='DELETE'){if(!u||u.role!=='super_admin')return json(res,403,{error:'Super Admin required'});db.prepare('DELETE FROM admin_roles WHERE id=?').run(+rr[1]);return json(res,200,{ok:true})}
if(p==='/api/admin/users'&&method==='GET'){if(!u||u.role!=='super_admin')return json(res,403,{error:'Super Admin required'});return json(res,200,db.prepare("SELECT id,name,email,role,active,created_at FROM users WHERE role!='customer' ORDER BY id").all())}
if(p==='/api/admin/users'&&method==='POST'){if(!u||u.role!=='super_admin')return json(res,403,{error:'Super Admin required'});let b=await parseBody(req);if(!b.name||!b.email||!b.password||!b.role)return json(res,400,{error:'Name, login, password and role required'});if(db.prepare('SELECT id FROM users WHERE email=?').get(b.email))return json(res,409,{error:'Login already exists'});let r=db.prepare('INSERT INTO users(name,email,password_hash,role,active,created_at) VALUES(?,?,?,?,1,?)').run(b.name,b.email,hash(b.password),b.role,now());return json(res,201,{id:Number(r.lastInsertRowid)})}
let au=p.match(/^\/api\/admin\/users\/(\d+)$/);if(au&&method==='PUT'){if(!u||u.role!=='super_admin')return json(res,403,{error:'Super Admin required'});let b=await parseBody(req);db.prepare('UPDATE users SET role=coalesce(?,role),active=coalesce(?,active) WHERE id=?').run(b.role??null,b.active??null,+au[1]);return json(res,200,{ok:true})}
if(p==='/api/admin/reports'&&method==='GET'){if(!u||u.role==='customer')return json(res,401,{error:'Admin login required'});let from=url.searchParams.get('from')||'',to=url.searchParams.get('to')||'',where=(alias='')=>{let col=(alias?alias+'.':'')+'created_at',w=[],pa=[];if(from){w.push(`date(${col})>=date(?)`);pa.push(from)}if(to){w.push(`date(${col})<=date(?)`);pa.push(to)}return {sql:w.length?' WHERE '+w.join(' AND '):'',pa}};let vw=where('v'),ew=where('e'),iw=where('i'),ow=where('o'),cw=where('c'),mw=where('m');let inventory=db.prepare(`SELECT v.* FROM vehicles v${vw.sql} ORDER BY v.created_at DESC`).all(...vw.pa),enquiryRows=db.prepare(`SELECT e.*,v.title vehicle_title FROM enquiries e LEFT JOIN vehicles v ON v.id=e.vehicle_id${ew.sql} ORDER BY e.created_at DESC`).all(...ew.pa),inspectionRows=db.prepare(`SELECT i.*,v.title vehicle_title FROM inspections i LEFT JOIN vehicles v ON v.id=i.vehicle_id${iw.sql} ORDER BY i.created_at DESC`).all(...iw.pa),orderRows=db.prepare(`SELECT o.* FROM orders o${ow.sql} ORDER BY o.created_at DESC`).all(...ow.pa),customers=db.prepare(`SELECT count(*) count FROM customers c${cw.sql}`).get(...cw.pa).count,chat=db.prepare(`SELECT count(*) count FROM chat_messages m${mw.sql}`).get(...mw.pa).count;return json(res,200,{from,to,inventory,enquiryRows,inspectionRows,orderRows,customers,chat})}
if(p==='/api/admin/search'&&method==='GET'){if(!u||u.role==='customer')return json(res,401,{error:'Admin login required'});let q='%'+(url.searchParams.get('q')||'').trim()+'%';return json(res,200,{vehicles:db.prepare('SELECT id,title,status,price FROM vehicles WHERE title LIKE ? OR make LIKE ? OR model LIKE ? LIMIT 20').all(q,q,q),products:db.prepare("SELECT id,name,category,price FROM products WHERE status!='Deleted' AND (name LIKE ? OR category LIKE ? OR description LIKE ?) LIMIT 20").all(q,q,q),customers:db.prepare('SELECT id,name,email,phone FROM customers WHERE name LIKE ? OR email LIKE ? OR phone LIKE ? LIMIT 20').all(q,q,q),requests:db.prepare('SELECT id,name,make,model,status FROM car_requests WHERE name LIKE ? OR make LIKE ? OR model LIKE ? LIMIT 20').all(q,q,q)})}
if(p==='/api/analytics/dashboard'){let stats={vehicles:db.prepare("SELECT count(*) n FROM vehicles WHERE status='Available'").get().n,totalVehicles:db.prepare('SELECT count(*) n FROM vehicles').get().n,enquiries:db.prepare('SELECT count(*) n FROM enquiries').get().n,inspections:db.prepare('SELECT count(*) n FROM inspections').get().n,customers:db.prepare('SELECT count(*) n FROM customers').get().n,requests:db.prepare('SELECT count(*) n FROM car_requests').get().n,alerts:db.prepare('SELECT count(*) n FROM alerts').get().n,messages:db.prepare('SELECT count(*) n FROM contact_messages').get().n,views:db.prepare('SELECT coalesce(sum(views),0) n FROM vehicles').get().n,sold:db.prepare("SELECT count(*) n FROM vehicles WHERE status='Sold'").get().n};return json(res,200,{stats,vehicles:vehicleRows('1=1').slice(0,10),recentEnquiries:db.prepare('SELECT e.*,v.title vehicle_title FROM enquiries e LEFT JOIN vehicles v ON v.id=e.vehicle_id ORDER BY e.created_at DESC LIMIT 5').all(),recentInspections:db.prepare('SELECT i.*,v.title vehicle_title FROM inspections i LEFT JOIN vehicles v ON v.id=i.vehicle_id ORDER BY i.created_at DESC LIMIT 5').all()})}
if(p==='/api/audit'){return json(res,200,db.prepare('SELECT a.*,u.name user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 100').all())}

if(p==='/api/content/terms'&&method==='GET'){let x=db.prepare("SELECT * FROM content_blocks WHERE key='terms'").get();return json(res,200,x||{})}
if(p==='/api/content/terms'&&method==='PUT'){let b=await parseBody(req);db.prepare("INSERT INTO content_blocks(key,title,subtitle,body,extra_json,updated_at) VALUES('terms',?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET title=excluded.title,subtitle=excluded.subtitle,body=excluded.body,updated_at=excluded.updated_at").run(b.title||'',b.subtitle||'',b.body||'','[]',now());audit(u,'update','content','terms');return json(res,200,{ok:true})}
if(p==='/api/products'&&method==='GET')return json(res,200,db.prepare("SELECT * FROM products WHERE status!='Deleted' ORDER BY created_at DESC").all());
if(p==='/api/products'&&method==='POST'){let b=await parseBody(req),r=db.prepare('INSERT INTO products(name,category,description,price,stock,image,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(b.name,b.category||'',b.description||'',+b.price||0,+b.stock||0,b.image||'',b.status||'Active',now(),now());return json(res,201,{id:Number(r.lastInsertRowid)})}
let pm=p.match(/^\/api\/products\/(\d+)$/);if(pm&&method==='PUT'){let b=await parseBody(req),x=db.prepare('SELECT * FROM products WHERE id=?').get(+pm[1]);if(!x)return json(res,404,{error:'Not found'});for(const k of ['name','category','description','price','stock','image','status'])if(b[k]!==undefined)x[k]=b[k];db.prepare('UPDATE products SET name=?,category=?,description=?,price=?,stock=?,image=?,status=?,updated_at=? WHERE id=?').run(x.name,x.category,x.description,+x.price,+x.stock,x.image,x.status,now(),x.id);return json(res,200,{ok:true})}
if(pm&&method==='DELETE'){db.prepare("UPDATE products SET status='Deleted',updated_at=? WHERE id=?").run(now(),+pm[1]);return json(res,200,{ok:true})}
if(p==='/api/services'&&method==='GET')return json(res,200,db.prepare("SELECT * FROM services WHERE status!='Deleted' ORDER BY id").all());
if(p==='/api/services'&&method==='POST'){let b=await parseBody(req),r=db.prepare('INSERT INTO services(name,description,price_from,icon,status,created_at,updated_at,image) VALUES(?,?,?,?,?,?,?,?)').run(b.name,b.description||'',+b.price_from||0,b.icon||'🔧',b.status||'Active',now(),now(),b.image||'');return json(res,201,{id:Number(r.lastInsertRowid)})}
let sm=p.match(/^\/api\/services\/(\d+)$/);if(sm&&method==='PUT'){let b=await parseBody(req),x=db.prepare('SELECT * FROM services WHERE id=?').get(+sm[1]);if(!x)return json(res,404,{error:'Not found'});for(const k of ['name','description','price_from','icon','status'])if(b[k]!==undefined)x[k]=b[k];db.prepare('UPDATE services SET name=?,description=?,price_from=?,icon=?,status=?,updated_at=? WHERE id=?').run(x.name,x.description,+x.price_from,x.icon,x.status,now(),x.id);return json(res,200,{ok:true})}
if(sm&&method==='DELETE'){db.prepare("UPDATE services SET status='Deleted',updated_at=? WHERE id=?").run(now(),+sm[1]);return json(res,200,{ok:true})}
if(p==='/api/agents'&&method==='GET')return json(res,200,db.prepare("SELECT * FROM agents WHERE status!='Deleted' ORDER BY name").all());
if(p==='/api/agents'&&method==='POST'){let b=await parseBody(req),r=db.prepare('INSERT INTO agents(name,email,phone,image,bio,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(b.name,b.email||'',b.phone||'',b.image||'',b.bio||'',b.status||'Active',now(),now());return json(res,201,{id:Number(r.lastInsertRowid)})}
let am=p.match(/^\/api\/agents\/(\d+)$/);if(am&&method==='PUT'){let b=await parseBody(req),x=db.prepare('SELECT * FROM agents WHERE id=?').get(+am[1]);if(!x)return json(res,404,{error:'Not found'});for(const k of ['name','email','phone','image','bio','status'])if(b[k]!==undefined)x[k]=b[k];db.prepare('UPDATE agents SET name=?,email=?,phone=?,image=?,bio=?,status=?,updated_at=? WHERE id=?').run(x.name,x.email,x.phone,x.image,x.bio,x.status,now(),x.id);return json(res,200,{ok:true})}
if(am&&method==='DELETE'){db.prepare("UPDATE agents SET status='Deleted',updated_at=? WHERE id=?").run(now(),+am[1]);return json(res,200,{ok:true})}
if(p==='/api/orders'&&method==='POST'){if(!u||u.role!=='customer')return json(res,401,{error:'Please sign in to checkout'});let b=await parseBody(req),items=Array.isArray(b.items)?b.items:[];if(!items.length)return json(res,400,{error:'Cart is empty'});let total=0,valid=[];for(const it of items){let pr=db.prepare("SELECT * FROM products WHERE id=? AND status='Active'").get(+it.id);if(!pr||pr.stock<1)continue;let qty=Math.max(1,Math.min(+it.qty||1,pr.stock));total+=pr.price*qty;valid.push([pr,qty])}if(!valid.length)return json(res,400,{error:'No available items in cart'});let no='RAL-'+Date.now(),r=db.prepare('INSERT INTO orders(customer_id,order_no,total,status,payment_method,payment_status,delivery_address,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(u.id,no,total,'Pending Payment',b.payment_method||'Mobile Money','Pending',b.delivery_address||'',now(),now());for(const [pr,qty] of valid)db.prepare('INSERT INTO order_items(order_id,product_id,name,price,qty) VALUES(?,?,?,?,?)').run(r.lastInsertRowid,pr.id,pr.name,pr.price,qty);let ref='RALPAY'+Date.now(),secret=process.env.PAYSTACK_SECRET_KEY||setting('paystack_secret_key'),provider=setting('payment_provider','Paystack'),authUrl='';db.prepare('INSERT INTO payments(order_id,reference,method,amount,status,provider,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(r.lastInsertRowid,ref,b.payment_method||'Mobile Money',total,'Pending',provider,now(),now());if(secret&&provider==='Paystack'){try{let cb=setting('payment_callback_url',process.env.APP_URL?process.env.APP_URL+'/#account':'');let channels=b.payment_method==='Card'?['card']:['mobile_money'];let pr=await fetch('https://api.paystack.co/transaction/initialize',{method:'POST',headers:{authorization:'Bearer '+secret,'content-type':'application/json'},body:JSON.stringify({email:u.email,amount:String(Math.round(total*100)),currency:setting('payment_currency','GHS'),reference:ref,channels,callback_url:cb,metadata:JSON.stringify({order_id:Number(r.lastInsertRowid),order_no:no})})});let pd=await pr.json();if(pr.ok&&pd.status)authUrl=pd.data.authorization_url||''}catch(e){console.error('Paystack initialize failed',e.message)}}return json(res,201,{id:Number(r.lastInsertRowid),order_no:no,total,payment_reference:ref,payment_status:'Pending',authorization_url:authUrl,message:authUrl?'Continue to secure payment.':'Order created. Configure Paystack in Admin > Payment Setup to collect live payments.'})}
if(p==='/api/orders'&&method==='GET'){if(u.role!=='customer')return json(res,200,db.prepare('SELECT * FROM orders ORDER BY created_at DESC').all());return json(res,200,db.prepare('SELECT * FROM orders WHERE customer_id=? ORDER BY created_at DESC').all(u.id))}
if(p==='/api/service-requests'&&method==='POST'){if(!u||u.role!=='customer')return json(res,401,{error:'Please sign in to request a service'});let b=await parseBody(req),r=db.prepare('INSERT INTO service_requests(customer_id,service_id,name,phone,vehicle,preferred_date,notes,status,amount,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(u.id,+b.service_id||null,b.name||u.name,b.phone||'',b.vehicle||'',b.preferred_date||'',b.notes||'','New',0,now(),now()),id=Number(r.lastInsertRowid),svc=db.prepare('SELECT name FROM services WHERE id=?').get(+b.service_id),cid=requestConversation(u,'service_request',id,`${svc?.name||'Service'} request #${id}`,'Your service request has been received. Reply here to speak directly with the Revolt team.');notifyRequest(u,'service request',id,`${svc?.name||''} ${b.vehicle||''}`);return json(res,201,{id,conversation_id:cid})}
if(p==='/api/service-requests'&&method==='GET'){if(u.role!=='customer')return json(res,200,db.prepare('SELECT r.*,s.name service_name FROM service_requests r LEFT JOIN services s ON s.id=r.service_id ORDER BY r.created_at DESC').all());return json(res,200,db.prepare('SELECT r.*,s.name service_name FROM service_requests r LEFT JOIN services s ON s.id=r.service_id WHERE r.customer_id=? ORDER BY r.created_at DESC').all(u.id))}
if(p==='/api/payments'&&method==='GET')return json(res,200,db.prepare('SELECT * FROM payments ORDER BY created_at DESC').all());
if(p==='/api/chat/conversations'&&method==='POST'){if(!u||u.role!=='customer')return json(res,401,{error:'Please sign in to chat'});let b=await parseBody(req),r=db.prepare('INSERT INTO conversations(customer_id,subject,context_type,context_id,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(u.id,b.subject||'General enquiry',b.context_type||'general',String(b.context_id||''),'Open',now(),now());return json(res,201,{id:Number(r.lastInsertRowid)})}
if(p==='/api/chat/conversations'&&method==='GET'){if(!u)return json(res,401,{error:'Please sign in to chat'});if(u.role!=='customer')return json(res,200,db.prepare('SELECT c.*,u.name customer_name,u.email customer_email,(SELECT message FROM chat_messages m WHERE m.conversation_id=c.id ORDER BY id DESC LIMIT 1) last_message FROM conversations c LEFT JOIN users u ON u.id=c.customer_id ORDER BY c.updated_at DESC').all());return json(res,200,db.prepare('SELECT * FROM conversations WHERE customer_id=? ORDER BY updated_at DESC').all(u.id))}
let cm=p.match(/^\/api\/chat\/conversations\/(\d+)\/messages$/);if(cm&&method==='GET'){if(!u)return json(res,401,{error:'Sign in required'});let c=db.prepare('SELECT * FROM conversations WHERE id=?').get(+cm[1]);if(!c||!(u.role!=='customer'||c.customer_id===u.id))return json(res,403,{error:'Forbidden'});return json(res,200,db.prepare('SELECT * FROM chat_messages WHERE conversation_id=? ORDER BY id').all(c.id))}
if(cm&&method==='POST'){let c=db.prepare('SELECT * FROM conversations WHERE id=?').get(+cm[1]);if(!c||!(u.role!=='customer'||c.customer_id===u.id))return json(res,403,{error:'Forbidden'});let b=await parseBody(req);if(!String(b.message||'').trim())return json(res,400,{error:'Message required'});let sender=u.role!=='customer'?'admin':'customer';let r=db.prepare('INSERT INTO chat_messages(conversation_id,sender_type,sender_id,message,created_at) VALUES(?,?,?,?,?)').run(c.id,sender,u.id,String(b.message).trim(),now());db.prepare('UPDATE conversations SET updated_at=? WHERE id=?').run(now(),c.id);return json(res,201,{id:Number(r.lastInsertRowid)})}

return json(res,404,{error:'API route not found'})}
const types={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon','.webp':'image/webp','.mp4':'video/mp4','.webm':'video/webm','.mp3':'audio/mpeg','.wav':'audio/wav','.ogg':'audio/ogg'};

function refreshSmartAlertMatches(vehicleId){
 try{let v=db.prepare('SELECT * FROM vehicles WHERE id=?').get(vehicleId);if(!v||String(v.status).toLowerCase()!=='available')return;for(const a of db.prepare("SELECT * FROM alerts WHERE status='Active'").all()){let c={};try{c=JSON.parse(a.criteria||'{}')}catch{};let ok=true;if(c.make)ok=ok&&String(v.make||'').toLowerCase().includes(String(c.make).toLowerCase());if(c.model)ok=ok&&String(v.model||'').toLowerCase().includes(String(c.model).toLowerCase());if(+c.budget>0)ok=ok&&+v.price<=+c.budget;if(c.location)ok=ok&&String(v.location||'').toLowerCase().includes(String(c.location).toLowerCase());if(ok&&a.last_match_vehicle_id!==v.id)db.prepare('UPDATE alerts SET match_count=coalesce(match_count,0)+1,last_match_vehicle_id=? WHERE id=?').run(v.id,a.id)}
 }catch(e){console.error('Smart alert match failed',e.message)}
}
const server=http.createServer(async(req,res)=>{try{let u=user(req);if(req.url.startsWith('/api/'))return await api(req,res,u);let pathname=decodeURIComponent(new URL(req.url,'http://x').pathname);if(pathname.startsWith('/uploads/')){let uf=path.join(UPLOADS,path.basename(pathname));if(fs.existsSync(uf)){res.writeHead(200,{'content-type':types[path.extname(uf)]||'application/octet-stream','cache-control':'public, max-age=86400'});return fs.createReadStream(uf).pipe(res)}}let f=path.join(PUBLIC,pathname==='/'?'index.html':pathname);if(!f.startsWith(PUBLIC))return json(res,403,{error:'Forbidden'});if(!fs.existsSync(f)||fs.statSync(f).isDirectory())f=path.join(PUBLIC,'index.html');res.writeHead(200,{'content-type':types[path.extname(f)]||'application/octet-stream','cache-control':'no-cache'});fs.createReadStream(f).pipe(res)}catch(e){console.error(e);json(res,500,{error:'Server error'})}});
server.listen(process.env.PORT||3000,()=>console.log('Revolt AutoLink running on http://localhost:'+(process.env.PORT||3000)));
